### ISSUE TITLE
Good starting article around Research Software Engineers

### ISSUE THREAD

**Issue by rowlandm** [rse-aunz/rse-au#1]
https://sinews.siam.org/Details-Page/research-software-engineer-a-new-career-track

Yeah - I'm definitely not one.

**Comment by rowlandm** [comment]
Also here:

n case you haven’t seen this - https://www.software.ac.uk/what-do-we-know-about-rses-results-our-international-surveys

Results from 841 people in 5 countries.

**Comment by rowlandm** [comment]
Another report that might be of interest:

It’s that time of year again! We just launched the results of our 2018 Annual Developer Survey.

Over 100,000 respondents from around the world participated this year, making it the world’s largest and most comprehensive developer survey.

In the results, you'll learn...

•	This year’s most loved, dreaded and wanted technologies
•	How developers around the world code, learn, live and work
•	What your peers think about artificial intelligence.

https://insights.stackoverflow.com/survey/2018/?utm_source=Iterable&utm_medium=email&utm_campaign=dev-survey-2018-promotion

**Comment by amandamiotto** [comment]
All of the stack exchange blogs are insightful, they do some great analytics

**Comment by amandamiotto** [comment]
I just came across https://www.yammer.com/cauditresearchsupportcommunity#/home and https://www.caudit.edu.au/communities (looks like they've been around for years)

**Comment by manodeep** [comment]
Thanks @amandamiotto. I looked at their membership directory and looks like the members institutes are the same as [FAVeR](http://www.faver.edu.au/). From my two seconds of googling, can't tell them apart.

**Comment by manodeep** [comment]
Related about who are RSEs from the [UK RSE website](http://rse.ac.uk/)

Are you a Research Software Engineer?

Regardless of your formal job title, if you answer yes to many of the following questions, you are doing the work of a Research Software Engineer:

-    Are you employed to develop software for research?
-    Are you spending more time developing software than conducting research?
-    Are you employed as a postdoctoral researcher, even though you predominantly work on software development?
-    Are you the person who does computers in your research group?
-    Are you sometimes not named on research papers despite playing a fundamental part in developing the software used to create them?
-    Do you lack the metrics needed to progress your academic career, like papers and conference presentations, despite having made a significant contribution through software?

**Comment by manodeep** [comment]
Making the case for RSEs - a summary by Simon Hettrick (@SimonHettrick): https://www.software.ac.uk/blog/2018-04-11-secret-behind-growth-rse-groups-uk

**Comment by dylan-jayatilaka** [comment]
I have been waiting for a group like this to form for 30 years.

**Comment by rowlandm** [comment]
Welcome Dylan! If you would like to get involved, please let me know.

**Comment by dylan-jayatilaka** [comment]
Yes, I would - what to do?

--dylan

best regards,

--dylan

Prof. Dylan Jayatilaka
School of Chemistry and Biochemistry
The University of Western Australia
Office : +61 8 6488 3138
Lab     : +61 8 6488 4462
Mobile: +61 435 44 1001
Skype : dylan.jayatilaka
