### ISSUE TITLE
Create a list of the interim steering committee members

### ISSUE THREAD

**Issue by manodeep** [rse-aunz/rse-au#10]
We should probably have a listing of the interim steering committee in the root directory of this repo. I am hesitant to put any contact info though but can be convinced otherwise (perhaps the committee members can add their own contact info, **iff** they are fine with that)

**Comment by rowlandm** [comment]
Rowland Mosbergen rowland.mosbergen@nectar.org.au

**Comment by dylan-jayatilaka** [comment]
This is a funny place to do discussions. Don't you guys use Slack or something?

**Comment by manodeep** [comment]
Discussing here helps keep the process open and transparent; the discussion is also then stored for posterity. 

I figure that any important discussion might just get a summary into a separate file within the repo (containing a link back to the originating discussion)

**Comment by rowlandm** [comment]
I think gitter would be good to use and have that chat summarised in an issue or a document. We haven't really started looking at that...

**Comment by manodeep** [comment]
@rowlandm we have the AU-NZ slack channel on the RSE slackspace. I have never used gitter - I assume there are feature improvements over slack

**Comment by rowlandm** [comment]
oh sweet. Let's just use that then. Where is it?

**Comment by manodeep** [comment]
First request to join the UK RSE slack [here, google form linked on rse.ac.uk page](https://docs.google.com/forms/d/e/1FAIpQLSc9LqOWGwA1xDvSgy81eimcb9s0cNBFso0zv0_HoZz16G1M5w/viewform?c=0&w=1)

Then the channel is australia-new-zealand (which Nick May originally created)

**Comment by atruskie** [comment]
So I'll add the list of people on the steering committee as a file in a few days. I'll leave it for a few days so anyone can opt out if they like.

I'll use the format:

```
Name, Organization, Contact
```

Where contact can a twitter account, or email address etc...
I won't include email addresses by default (since I'm not a fan of email scraping).

**Comment by rowlandm** [comment]
You can add my nectar email account Anthony. thanks!
