### ISSUE TITLE
2018-05-22 Interim Steering Committee Meeting Agenda, Notes and Action Items

### ISSUE THREAD

**Issue by rowlandm** [rse-aunz/rse-au#12]
1. Perth f2f update
2. Plan f2f in other states
3.  1 day workshop on software skills/sustainability/something across the RSE community and ANDS/Nectar/RDS (Michelle Barker)
4. Promote RSEs at the 2018 eResearch conference (Sam Moskwa)
5. Other businesses- review hit issues
6. Communication, email contact list and/or chatroom?

**Comment by rowlandm** [comment]
7. Expectations of the committee https://github.com/rse-aunz/rse-au/issues/7

**Comment by rowlandm** [comment]
8. What to do with new volunteers? Dylan, Eric...

**Comment by manodeep** [comment]
What's the zoom link?

**Comment by nrmay** [comment]
https://monash.zoom.us/j/691412731

**Comment by rowlandm** [comment]
Notes from meeting:

- Lance to email Ryan Sullivan from NSW around being involved with the RSE steering committee

Face to face meeting organisations by state:
- VIC: Lance volunteered, also Nick Golding volunteered via #9 
- NSW: Any volunteers to organise?
- QLD: No face to face meetings until after ResBaz 
- SA, NT, TAS: No contacts available. 

- Rowland to email Sarah Nisbet and Paul Coddington around RSE contacts in SA.
- Heidi, Rowland and Sam to organise pre-conference workshop at eResearch Australasia. Think about international visitors.
- Nicholas May created an issue around C3DIS eresearch Workforce #13 to get some ideas down
- Communication: Rowland to encourage people like Dylan, Eric, Nick to joing the google group email list by providing a link and follow this github repository.  There is also an international RSE slack but I can't remember how I got access ....

**Comment by rowlandm** [comment]
Link to get to the google group email list:
https://groups.google.com/forum/#!forum/rse-nz-au

**Comment by rowlandm** [comment]
Link to the RSE Slack channel
https://docs.google.com/forms/d/e/1FAIpQLSc9LqOWGwA1xDvSgy81eimcb9s0cNBFso0zv0_HoZz16G1M5w/viewform?c=0&w=1

We definitely need a website!

**Comment by rowlandm** [comment]
Slack has a #australia-new-zealand channel.
