### ISSUE TITLE
eResearch Australasia workshop details.

### ISSUE THREAD

**Issue by rowlandm** [rse-aunz/rse-au#16]
Hi All,

I had a chat with Sam Moskwa around a RSE eResearch Australasia workshop.

Here are the action items:
https://docs.google.com/document/d/1V5ZHQeLzPYXa3ll2CJCZjXlKVFGLICdYpKKfVFxPbYk/edit#

Please have a look and discuss either here or in the document.

Rowland.

**Comment by lancewilson-monash** [comment]
The typical audience at eResearch is not academics who code but professional staff who code for academics. How do we engage with the other half of this group as this conference is unlikely to come up in searches they do for travel?

**Comment by manodeep** [comment]
I think we need to send around blurbs about the RSE community/events within University newsletters. That might be the quickest way to reach out to potential RSEs

**Comment by rowlandm** [comment]
Good idea.

**Comment by kerriwait** [comment]
@lancewilson-monash one approach that has been successful at Griffith* and UQ* has been the hacky hour concept, and in particular, reaching out to HDR schools/societies/groups within faculties. This of course assumes that you meant engaging with the "academics who code" group, albeit more of the ECR cohort than established academics. I'm certain Amanda would have valuable input on this aspect.

I like your idea @manodeep - I'd suggest that we compile case studies and then circulate those amongst the institutions that SC members have contacts in to begin with. 

Another important consideration is the number of data librarians and other research liaison staff who attend eResearch; bringing them into the community could provide us with even more engagement opportunities, as they're often in the trenches. Do you know if we've got any representation from the libraries @rowlandm?

*If I may be so bold as to speak on behalf of my former colleagues!

**Comment by amandamiotto** [comment]
I've done a little bit of a scout around at hacky hours in regards to researchers- even the researchers who are doing more advanced coding don't believe they are strong enough in their coding skills to be part of a RSE group. I'll keep working on them but if you find a strategy that works, let me know. We have very centralized IT, however if you didn't at your institute, that would be a good way of reaching those situated in research centers.

**Comment by goldingn** [comment]
We'll be running a Victorian meetup in Melbourne in early August, and I'm hoping to get a lot of academic RSEs to attend that (list of people to contact on the slack channel). We could definitely point attendees to the eResearch meeting.

Will people be able to attend the workshop without registering for the conference? If they have to register, that would likely be a major barrier to academics.

**Comment by rowlandm** [comment]
Hi Everyone,

This looks like the final versions of the BoF and the pre-conference workshop for eResearch Australasia. Could you all please have a final look and I will submit this on Thursday close of business.

BoF:
https://docs.google.com/document/d/1HS7CvbsES-1hy0W9TefgYHsZXMd49FqkmLqfe0V74yw/edit

Workshop:
https://docs.google.com/document/d/1xQyBUS-nQbwIUnt5bGas28Y-DNCZzUWHgKIJOQweLFY/edit

**Comment by rowlandm** [comment]
> Another important consideration is the number of data librarians and other research liaison staff who attend eResearch; bringing them into the community could provide us with even more engagement opportunities, as they're often in the trenches. Do you know if we've got any representation from the libraries @rowlandm?

@kerriwait  - not many representations from the libraries at this point, but there is nothing stopping us from contacting them apart from time at the moment.

**Comment by rowlandm** [comment]
> We'll be running a Victorian meetup in Melbourne in early August, and I'm hoping to get a lot of academic RSEs to attend that (list of people to contact on the slack channel). We could definitely point attendees to the eResearch meeting.

Will people be able to attend the workshop without registering for the conference? If they have to register, that would likely be a major barrier to **academics.**

@goldingn  - good point. I think they can attend without having to register...

**Comment by rowlandm** [comment]
Fantastic. I'll get confirmation for that via the conference organisers.

**Comment by rowlandm** [comment]
@goldingn  - confirmation from Conference Design

> Both delegates and non-delegates will be able to register for the pre-conference workshops. As this will be at an additional cost, basically anyone can attend.

**Comment by amandamiotto** [comment]
Is the plan to charge for this day or keep it free?

**Comment by rowlandm** [comment]
Charge. We don't have any financial backing....

**Comment by manodeep** [comment]
@rowlandm Do you have any estimate of the cost?

**Comment by rowlandm** [comment]
Not yet. It hasn't been posted on the website yet.
