### ISSUE TITLE
2018-06-26 Interim Steering Committee monthly meeting

### ISSUE THREAD

**Issue by rowlandm** [rse-aunz/rse-au#18]
Zoom link is here:
https://unimelb.zoom.us/j/6552003787

Please add any agenda items under this comment.

**Comment by rowlandm** [comment]
From Manodeep:
1. One or two Australian members from the Steering Committee to participate in the international RSE survey and adapt the design for the Australian context
2. Nooriyan from NeSI would like to attend the monthly Steering Committee meetings
3. Think about a domain name (i.e., webpage) and webpage contents up. Could be very bare-bones for now

**Comment by rowlandm** [comment]
NeSI is working with members of the NZ RSE community to put on our annual Science Coding Conference. The conference is for anyone coding for research with a primary focus on providing a forum for attendees to meet people in similar roles as themselves, share successes and challenges, tips and tricks. Our Australian peers would be more than welcome to join us for this community development event as well.

Join us for the 2018 Science Coding Conference in Rotorua August 1-3, 2018.

**Comment by rowlandm** [comment]
Building a RSE community in South Australia

**Comment by rowlandm** [comment]
NSW Face to Face meeting
QLD Face to Face meeting

**Comment by manodeep** [comment]
Regarding agenda item #1, there is an initial skype meeting tomorrow from 5-6 pm Melbourne time.

**Comment by manodeep** [comment]
At the last RSE meeting, we had discussed about potential ways to reach out to academics who code. I had thrown up the idea of sending out a blurb about RSE and upcoming RSE-related events on various University newsletters. Do we want to flesh out such a blurb and advertise the Victoria F2F?

**Comment by rowlandm** [comment]
Agenda item: Agreeing that we should invite the people who attended the Perth F2F to the google groups email list.

**Comment by goldingn** [comment]
Agenda item: discussing how best to run F2Fs (including contents of Victorian F2F).

**Comment by jimmybgammyknee** [comment]
Sorry for not being able to get to this first meeting. Will make sure someone from SA attends the next
