### ISSUE TITLE
QLD face to face meeting discussion

### ISSUE THREAD

**Issue by rowlandm** [rse-aunz/rse-au#19]

**Comment by MilesMcBain** [comment]
I'll put my hand up as an organiser of the Brisi meet.

**Comment by MilesMcBain** [comment]
Haha @amandamiotto I was going to email you about this. Awesome!

Any thoughts Re dates? It would be good to keep up momentum from the previous meets. September would be do-able for me. Things get a bit hectic for me from mid Oct to late Nov, would prefer to work around that.

**Comment by amandamiotto** [comment]
Mid Oct to mid Nov I'm on leave anyway so that works. 

14th Sept there is health hack in the afternoon/night and 17-18th Sept there is a CSIRO/Data61 conference. We could either avoid these days or try and align/leverage off those events (I'm involved with Health hack this year too).

I've got quite a few advertising channels once we're set up.

**Comment by rowlandm** [comment]
The CSIRO conference would be great to leverage off!

**Comment by amandamiotto** [comment]
I'm free all next Friday if you'd like to Zoom then?

Due to my workload, I'm probably not going to be a big help organizing pre-event, but I can definitely help facilitate on the day, bounce ideas and do advertising. I was hoping my workload would ease off after Resbaz but I keep finding things to get involved with (everything is so exciting and fun!). 

Rowland, will do.

**Comment by rowlandm** [comment]
3pm next Friday is free for me, but it's more important what day/time Miles
is free :)

**Comment by MilesMcBain** [comment]
So we're talking Friday the 31st of August to be clear? That time is good for me.

**Comment by rowlandm** [comment]
yep. I'll send an invite.  who else wants to be part of this?

**Comment by rowlandm** [comment]
Sent out an invite. Sam, please let me know if you got it.

Also I may be late, so just start without me!

**Comment by goldingn** [comment]
@rowlandm we're booked in to meet for the hour before this, right? How about I come over to your office for that, and I can join this call from your end at 3pm?

**Comment by rowlandm** [comment]
Yeah that's right. How about the other way around? I can head over to your
building?

**Comment by goldingn** [comment]
Deal. I've booked a room, will email the location.

**Comment by rowlandm** [comment]
no worries

**Comment by MilesMcBain** [comment]
Sorry everyone. I am home sick today with my son and couldn't get on the call.

**Comment by rowlandm** [comment]
I reckon that is OK. I don't think there are other solutions?

**Comment by manodeep** [comment]
The original idea was to work off of the CSIRO/Data61 gathering on the 17-18th; however, if there are no rooms available, then postponing makes sense. 

We haven't yet made the announcement for the QLD F2F. Ideally, we should have at least 2-3 weeks between the announcement and the event.

**Comment by MilesMcBain** [comment]
Did we confirm this for the 28th?

**Comment by atruskie** [comment]
AFAIK no confirmation so far. From the advertising perspective, we've only got a week left before the 28th and additionally, the 28th is in semester break.

Can we do a quick vote from the locals (@SamHames, @MilesMcBain, @amandamiotto, @weaverbel), does the 28th work for you (👍) or would you prefer another date (👎)? 

If it is for the 28th, we'll need to start advertising straight away.

@SamHames any possibility of the following week (2010-10-02 - 2010-10-05)?

**Comment by amandamiotto** [comment]
Just a FYI, I'm available Friday of those two weeks but after that I'm away for a month (also away next week but happy to come along Friday).


We probably needed to start advertising last week if we were going to go ahead for next Friday.


Amanda Miotto | Senior eResearch Analyst


eResearch Services- Office of Digital Solutions

Griffith University/ QCIF | Nathan | QLD 4111

T +61 7 373 54697 | @amandamiottoGU |

 a.miotto@griffith.edu.au

Hacky Hour: Griffith.edu.au/hackyhour | @hackyhourGU



Griffith University - CRICOS Provider Number 00233E


PRIVILEGED - PRIVATE AND CONFIDENTIAL

This email and any files transmitted with it are intended solely for the use of the addressee(s) and may contain information which is confidential or privileged. If you receive this email and you are not the addressee or responsible for delivery of the email to the addressee(s), please disregard the contents of the email, delete the mail and notify the author immediately.


________________________________

**Comment by MilesMcBain** [comment]
I think that's right, I'd say it needs a couple of weeks lead time. As I understand it, it was the promotion effort that lead to the success of the Melbourne meetup.

**Comment by MilesMcBain** [comment]
I'm available in the first two weeks of October, If we wanted to push it back.

**Comment by manodeep** [comment]
Is the consensus then Oct 5? If so, @mingfangwu can then add the that date on the newsletter coming out tomorrow. 

@amandamiotto @MilesMcBain @atruskie @SamHames

**Comment by mingfangwu** [comment]
@MilesMcBain Could you please let me know location, contact and time for the QLD f2f meeting if you would like ARDC to include the event in the newsletter going out tomorrow. Thanks!

**Comment by atruskie** [comment]
Okay, I've gone ahead and booked a room for the 5th of October. Booked from 15:00-17:00. It is a collaborative workspace room that holds 30-54. The room is GP-P-413.

There were some other options available.

It appears everyone is really busy (which is understandable) but we're again running out of time. I reckon we need to start advertising by the end of the day. I can devote an hour or two today but I'm not very confident in what I need to do to get this started. Help wanted, please.

**Comment by atruskie** [comment]
@mingfangwu, I noticed that ARDC made the last eventbrite, can you do so for this meeting as well?

Assuming @rowlandm doesn't mind, I've lifted the text they wrote for the event and modified it for QLD.

- Title:
> Queensland RSE Community Meeting - Recognition for Researchers who Code
- Date: 2018-10-05, 15:00 AEST to 17:00 AEST
- Location:
> GP-P-413
> QUT Gardens Point
> 2 George St
> Brisbane 4000
- Description:

> This meeting is to build awareness of the Research Software Engineer (RSE) community and to identify volunteers to help implement the practical solutions for the RSE community. If you are an academic/researcher who codes but are lacking recognition and metrics needed to progress your academic career; a professional software engineer working in the research space; or a system administrator who maintains research systems, you should think about joining.
> 
> The term RSE, originally coined by the UK RSE association (<rse.ac.uk>), says the following about RSEs: “A growing number of people in academia combine expertise in programming with an intricate understanding of research. Although this combination of skills is extremely valuable, these people lack a formal place in the academic system.”
> 
> Inspired by the success of the RSE Association in UK, we are seeking to establish an Australasian Chapter of the RSE Association. Together with international bodies and support from our national organisations such as AeRO, NeSI, CAUDIT, the Australian Research Data Commons (ARDC), and research institutions, we aim to campaign for the recognition and adoption of the RSE role within the research ecosystem. Alongside this, appropriate recognition, reward and career opportunities for RSEs are needed. We plan to organise regular events to allow RSEs to meet, exchange knowledge and collaborate on methods to create these opportunities.
> 
> We ran an initial Expression of Interest survey in 2017 among Australian and New Zealand researchers and found that majority of the respondents prioritised: (1) Increased recognition of the RSE role, (2) More appropriate, consistent and representative position descriptions and KPIs, and (3) Community development through regular events and gatherings.
> 
> Please join us to actively work on how we can grow this community and advocate for others. Together, we can build a sustainable community that benefits research software engineers and ultimately contributes to more efficient and reproducible research.
> 
> You can see our website here: https://rse-aunz.github.io/
> 
> and you can see what we have been discussing as a community here: https://github.com/rse-aunz/rse-au/issues
> 
> and you can join our mailing list here: https://groups.google.com/d/forum/rse-nz-au

I've also created a blog post (which needs to be updated after the eventbrite is created): https://github.com/rse-aunz/rse-aunz.github.io/pull/2

**Comment by MilesMcBain** [comment]
Okay we're go for the 5th! That's good for me. Awesome.

**Comment by mingfangwu** [comment]
@atruskie @MilesMcBain Sure, I can help to create an event at eventbrite.

I just strike me that we have a [TechTalk on 5th Oct](https://www.meetup.com/monthlytechtalk/events/253444761/). Would the two events "fight" developers from each other?

**Comment by MilesMcBain** [comment]
I don't have a sense of the overlap of the audiences. There's slides available, so that means one can still keep up with what is going on and come to our meeting.

**Comment by atruskie** [comment]
Ah, that is unfortunate, I didn't notice the conflict. I'm not sure of the audience overlap either. Does anyone have access to the list of attendees to the tech talk to estimate the how many people we'd lose?

I'm pretty sure there's no time or date that would resolve the conflict. The 5th is the last date that is good for the locals in this thread. An earlier afternoon/morning session means the day would be a write-off for me and I suspect others as well.

As @MilesMcBain pointed out, publishing the slides/video from the tech talk seems like a decent alternative.

**Comment by mingfangwu** [comment]
@atruskie @MilesMcBain Sure.

Here is the link to the evenbrite: https://www.eventbrite.com.au/e/queensland-rse-community-meeting-recognition-for-researchers-who-code-tickets-50673953158

**Comment by MilesMcBain** [comment]
I just registered. No problems. It's useful that it collects affiliations and job titles. :+1:

**Comment by atruskie** [comment]
Thanks, @mingfangwu. I've updated the blog post Can I get a maintainer of the gh-pages site to merge that?

I've also registered.

**Comment by mingfangwu** [comment]
@weaverbel Thanks! I will ask our communication officer to tweet it tomorrow then.

**Comment by amandamiotto** [comment]
Just got back from leave. I'll email it out today to our hacky hour crew and its already been published internally to eResearch at Griffith.


Thanks!


Amanda Miotto | Senior eResearch Analyst


eResearch Services- Office of Digital Solutions

Griffith University/ QCIF | Nathan | QLD 4111

T +61 7 373 54697 | @amandamiottoGU |

 a.miotto@griffith.edu.au

Hacky Hour: Griffith.edu.au/hackyhour | @hackyhourGU



Griffith University - CRICOS Provider Number 00233E


PRIVILEGED - PRIVATE AND CONFIDENTIAL

This email and any files transmitted with it are intended solely for the use of the addressee(s) and may contain information which is confidential or privileged. If you receive this email and you are not the addressee or responsible for delivery of the email to the addressee(s), please disregard the contents of the email, delete the mail and notify the author immediately.


________________________________

**Comment by MilesMcBain** [comment]
Hi all I am a bit unclear on the agenda for the meeting.

Are there some slides to go through initially? Or a foreword about RSE progress elsewhere?

Then we break to consider the github issues? Anything else?

**Comment by atruskie** [comment]
I'm doing the presentation and I've got Manodeep's slides which I'm slightly changing.

I've also procured a giant post-it/easel pad thing and some markers to discuss the questions that were done in the Vic F2F. We may need more butcher paper/markers so if you have spares please bring them.

I'm not clear on what "warm-up" exercise we will do.

Given the numbers attending we probably will only have two groups.

**Comment by mingfangwu** [comment]
@atruskie that sounds great! Good luck! ;-)

**Comment by amandamiotto** [comment]
I can bring some butchers papers and markers.


Amanda Miotto | Senior eResearch Analyst


eResearch Services- Office of Digital Solutions

Griffith University/ QCIF | Nathan | QLD 4111

T +61 7 373 54697 | @amandamiottoGU |

 a.miotto@griffith.edu.au

Hacky Hour: Griffith.edu.au/hackyhour | @hackyhourGU



Griffith University - CRICOS Provider Number 00233E


PRIVILEGED - PRIVATE AND CONFIDENTIAL

This email and any files transmitted with it are intended solely for the use of the addressee(s) and may contain information which is confidential or privileged. If you receive this email and you are not the addressee or responsible for delivery of the email to the addressee(s), please disregard the contents of the email, delete the mail and notify the author immediately.


________________________________

**Comment by MilesMcBain** [comment]
I've printed the GH issues. Also have a couple of ice-breakers up my sleeve.

**Comment by atruskie** [comment]
We ran the QLD F2F on 2018-10-05. 
So we had 8 people attend, all of which I would say are well versed in the topic of RSEs. Of the 8 people, 2 were on the interim steering committee, and 4 were software carpentry instructors.

We didn't take notes but there were some interesting conversations:
- Given that the room was filled with well-informed people, we suggested that what we really wanted to do is get that room to reach out to all the people they know that aren't aware of what an RSE is
- One person did not _want_ to identify as an RSE, even though they hit most of the checklist, fearing that would actually harm their future career prospects (branding issue, not enough of a recognised role, too tied to "research")
- We had an interesting conversation on "3rd space professionals". It boiled down to: RSEs are 3rd space professionals, but not all 3rd space professionals are RSEs
- One or two people didn't define themselves as RSEs but saw value in it
- One of the most discussed topics is how do we define an RSE?
   - _Do you work with or for the researchers?_: If you informed the research you were an RSE, if you didn't you were a more typical professional
   - _Can your job be defined with a traditional title? Then maybe you don't need the RSE label_. Jobs like _System Administrator_, or _buisness analyst_ are well defined, and well understood and thus shouldn't be labelled as RSEs
   - It was generally accepted that all the definitions were fuzzy: there's a spectrum of people that exist somewhere on the academic<-->professional axis, and somewhere on the expert<-->novice scale:
![spectrum](https://user-images.githubusercontent.com/1452968/46588932-32014400-cae7-11e8-8db2-f0be72cbbecc.png)
- Some of us went to the bar and got a beer afterwards. There was some interesting conversation on careers, and research related geeky stuff.

I'll be uploading the photos to the workshop questions in their respective issues.

If anyone else that attended can remember anything of note, please leave a comment.
