### ISSUE TITLE
2018-07-24 Interim Steering Committee Meeting

### ISSUE THREAD

**Issue by rowlandm** [rse-aunz/rse-au#26]
2pm Melbourne time 24th July 2018

Agenda:

- Rowland is leaving ARDC on the 27th of July. Mingfang will be helping out with the community in his place. Issue here https://github.com/rse-aunz/rse-au/issues/28
- Discussion of other things needed for Victorian Face to Face meeting (eg. Zoom for external participants)
- Suggest a welcoming person whose job it is to chase up questions from the community (eg. from Kerensa and Bill via github issues)
- Look at engaging the community around a CWL subcommitee/group https://github.com/rse-aunz/rse-au/issues/27
- eResearch Australasia pre-conference workshop has been approved.

**Comment by manodeep** [comment]
I have an item to add. 

- Overview of the international RSE survey and adapting for the Australian context

**Comment by rowlandm** [comment]
- Official approval of the website at https://rse-aunz.github.io/

**Comment by goldingn** [comment]
Some sub-bullets for the Vic F2F discussion:
 - structure for the presentation components (who to give an RSE overview?)
 - plan for the interactive/discussion components (do we need 'activities'?)
 - how to sign up attendees (to google group? via paper sign-up sheets?)
 - access to attendee list to find speakers?
 - setting up zoom meeting

**Comment by rowlandm** [comment]
I think we should have one facilitator and maybe 1 speaker. I think we need to engage the room and reduce the time taken to swap speakers etc. But that's just my opinion. Would be good to get feedback from Valerie Maxwell or people who were at the Perth Face ot Face, although that was only 12 people or so.

**Comment by goldingn** [comment]
Yeah, that's similar to what I was thinking: one person to talk about the RSE definition & progress in the UK/elsewhere. Then perhaps encourage discussion by prepping a handful people to give their (short, no slides) perspectives/experiences on the issues, then opening the floor to others.

Splitting into smaller groups (depending on number of attendees) to discuss issues and ways forward would allow more people to contribute/engage.

There's also a little group activity I've been in a couple of times that seems quite effective at that, and would also give feedback on how attendees identify (e.g. as eResearchers, academic/professional, coders/devs, RSEs/not). Can discuss that on the call.

**Comment by rowlandm** [comment]
Awesome! That sounds really great. Thanks Nick!

**Comment by jimmybgammyknee** [comment]
Apologies if this has been mentioned before, but what time is this happening tomorrow?

**Comment by rowlandm** [comment]
2pm Melbourne time.

**Comment by manodeep** [comment]
[Zoom link](https://unimelb.zoom.us/j/6552003787) for today from @mingfangwu

**Comment by rowlandm** [comment]
SIgn up sheet at the meeting. Good idea @goldingn

**Comment by atruskie** [comment]
@rowlandm: "it's not research but it is fundamental to research, with a focus on technology"

**Comment by dylan-jayatilaka** [comment]
Sorry to miss this. I thought I had the EST time listed, but actually I had the correct WST time ... :-(.
Thanks for the meeting notes.

**Comment by rowlandm** [comment]
No worries!

Regards,

*Rowland Mosbergen*
Manager, Community Platforms  | *Australian Research Data Commons*
E: rowland.mosbergen@nectar.org.au | W: www.ardc.edu.au
Twitter: @rowlandm




On Wed, Jul 25, 2018 at 11:54 AM, Dylan Jayatilaka <notifications@github.com

**Comment by mingfangwu** [comment]
@goldingn @rowlandm 

For the sign up sheet, I can print those people who registered at the Eventbrite for them to tick off.  An empty sign up sheet for those who hasn't signed up to the Eventbrite.  

Cheers,
Ming

**Comment by rowlandm** [comment]
Great idea!

**Comment by goldingn** [comment]
Did people who signed up via Eventbrite give permission to be signed up? I don't remember doing that.

If not, it would be better to get everyone to sign up afresh I think.
