### ISSUE TITLE
Rowland handover

### ISSUE THREAD

**Issue by rowlandm** [rse-aunz/rse-au#28]
Hi All,

I will be transitioning to a full time role at UoM and will therefore not be able to continue to chair and provide followup for the RSE community. I wanted to write down all the things that need to be handed over:

**Organising the monthly meetings**
- Sending emails to the committee
- Contact list of the emails for the committee members
- Using my own Zoom meeting room id
- Creating an issue in github for the agenda
- Calendar meeting needs to be updated with another owner

**Followup**
- Following up queries made by the committee and the community
- Following up on upcoming face to face meetings
- Approving of new members to the Google Groups is already being done by others.

**Website**
- Maintaining website at https://rse-aunz.github.io/

**eResearch Australasia 2018**
- Rowland has permission to continue to chair the preconference meeting, but won't be able to followup.
- Rowland can still be a part of the BoF, but won't be able to followup.

It would be great to discuss this in the next committee meeting https://github.com/rse-aunz/rse-au/issues/26

**Comment by rowlandm** [comment]
- Perhaps a fortnightly/monthly email that talks about some of the things we have been doing would be of use too.

**Comment by atruskie** [comment]
I can help maintain the website

**Comment by squarcleconsulting** [comment]
Greetings all,
Jens Klump from CSIRO sent the following to the google group but was rejected.  Appreciate it if someone in this group can pipe the message to the group.  With thanks, Paul.

-----Original Message-----
From: Klump, Jens (Mineral Resources, Kensington WA)
Sent: Tuesday, 31 July 2018 8:22 AM
To: 'rse-nz-au@googlegroups.com' <rse-nz-au@googlegroups.com>
Subject: FW: RSE Townhall blog post & survey

Hi all,

Here is a summary of the RSE activities in Europe and the townhall meeting held at the European Geosciences Union General Assembly earlier this year.

Regards

Jens

--
Dr Jens Klump
E jens.klump@csiro.au T +61 8 6436 8828 CSIRO ARRC, 26 Dick Perry Avenue, Kensington, WA 6151, Australia

-----Original Message-----
From: Daniel Nüst [mailto:daniel.nuest@uni-muenster.de]
Sent: Monday, 30 July 2018 8:36 PM
Subject: RSE Townhall blog post & survey

Dear participants of the RSE Townhall Meeting at the EGU General Assembly 2018,

it took some time but now a blog post and survey following up on our meeting in Vienna earlier this year are online:

http://www.de-rse.org/blog/2018/07/30/rses-at-egu-ga.html

Please also consider taking a few minutes to fill out the survey, also linked at the end of the article: 
http://nuest.staff.ifgi.de/survey/index.php/598158?lang=en


Thanks again for getting this group started and going - please spread the word!

Best regards,
Daniel

--
Daniel Nüst
Institute for Geoinformatics (ifgi),   University of Münster
Heisenbergstraße 2, 48149 Münster, Germany; +49 251 83 31962
http://ifgi.uni-muenster.de/~d_nues01        http://o2r.info

**Comment by manodeep** [comment]
@squarcleconsulting My guess is that Jens is not a member of the RSE googlegroup. I have sent him an invite.
