### ISSUE TITLE
Collect use cases of academics getting credit for software

### ISSUE THREAD

**Issue by rowlandm** [rse-aunz/rse-au#3]
Provide a centralised place to collect use cases, especially around academics getting credit, or institutions who are doing it well. eg Journal of Open Source Software

Action item 3 from:
https://github.com/rse-aunz/rse-au/issues/2

**Comment by amandamiotto** [comment]
Case: Open Heart Project https://openheartproject.org/

This is a project where researchers collaborate on 3d printable models of heart pumps, publishing testing scripts and data and work together on an open source model. They use Bitbucket and Confluence to do most of their work. 

What Jo Pauls hasdone is contact the editor of the journal ‘Artificial Organs’, which is the main journal of their research society ‘International Society for Mechanical Circulatory Support’.

In future journal publications that arise from work presented within OpenHeart they will include a link to a git repo on Bitbucket in the article to reference / link to complimentary files.

**Comment by amandamiotto** [comment]
From one of my researchers:

last hacky hour you had asked for examples of software/code development and the credit for the developers.

David (Hamilton) and I are members in GLEON (www.gleon.org, the Global Lake Ecological Observatory Network). The network uses sensors to collect high-frequency data in lakes, which can add up to a relatively large amount of data.
Within this network a few R software packages have been developed to analyse data. These are also used outside of GLEON.

One example that has worked very well is the LakeAnalyzer by Read. et al. This software package was developed first in Matlab, but was then translated into R. It was published together with a paper (now cited about 180 times), explaining all the physics and equations. I'll attach the paper.

Another nice example is a toolbox that was developed by a sister-network (Netlake):
https://www.dkit.ie/ga/node/13916
However, I think this only refers to the software, but doesn't publish any software.
Two R packages were developed to run a lake model and process its output (GLMr and glmtools). I think these are widely used, but there is no paper that went along and although many people use it, it is mainly one or two guys maintaining it.

Hope this is useful.
Cheers,
Marieke
A few other papers:

General on that topic:
Read, J. S.; Gries, C.; Read, E. K.; Klug, J.; Hanson, P. C.; Hipsey, M.; Jennings, E.; O'Reilley, C.; Winslow, L. A.; Pierson, D. & others
Generating community-built tools for data sharing and analysis in environmental networks
Inland Waters, 2016, 6, 637-644 
Two other software packages:
Woolway, R. I.; Jones, I. D.; Hamilton, D. P.; Maberly, S. C.; Muraoka, K.; Read, J. S.; Smyth, R. L. & Winslow, L. A. Automated calculation of surface energy fluxes with high-frequency lake buoy data
Environmental Modelling & Software, 2015, 70, 191 - 198


Winslow, L. A.; Zwart, J. A.; Batt, R. D.; Dugan, H. A.; Woolway, R. I.; Corman, J. R.; Hanson, P. C. & Read, J. S. LakeMetabolizer: An R package for estimating lake metabolism from free-water oxygen using diverse statistical models Inland Waters, 2016, 6, 622-636

**Comment by atruskie** [comment]
So far we've been lucky enough to collaborate with people who are willing to include me as a co-author. Attached with that is a little more responsibility (editing the paper, writing a few paragraphs) but it is definitely worthwhile for us.

Here are two papers where this has been the case (note they are in biololgy/ecology pubs which is way outside my field):

>Burivalova, Z., Towsey, M., Boucher, T., Truskinger, A., Apelis, C., Roe, P., & Game, E. T. (2017). Using soundscapes to detect variable degrees of human influence on tropical forests in Papua New Guinea. Conservation Biology. doi:10.1111/cobi.12968 

>Bradley Law, Gabriele Caccamo, Paul Roe, Anthony Truskinger, Traecey Brassil, Leroy Gonsalves, Anna McConville, Matthew Stanton. Development and field validation of a regional, management-scale habitat model: A koala Phascolarctos cinereus case study. Ecology and Evolution. doi:10.1002/ece3.3300 

This model, while nice, is unsustainable. We're trying to transition to using a citation + DOI for our software, especially now that we've publically released our software. I'm not sure how well this will work - we'll definitely get less authorships, and I think it'll be harder to track the citations. One benefit of a citation is that more developers can benefit from a ciation. We'll see  how it works out.

**Comment by manodeep** [comment]
Another way for getting credit is publishing short articles about open-source software via [JOSS](http://joss.theoj.org/). Of course, that only works if the software is open-source, which may not be always possible

**Comment by atruskie** [comment]
@manodeep absolutely - it is on my to-do list. While I hear it is very easy, because it requires more than 0 effort, it has put me off.

**Comment by GerryRyder** [comment]
I have been watching with interest the progress being made by the [Force 11 Software Citation Implementation Group](https://www.force11.org/group/software-citation-implementation-working-group).  I'm reminded of where we were a few years back with data citation, and how far that has come especially wrt things like academic [publisher policies](https://www.nature.com/authors/policies/availability.html).   Also, new avenues for publishing data as a first class output eg. [Nature Scientific Dat](https://www.nature.com/sdata/)a   Software looks to be going down a similar path with the help of initiatives like Force 11.

**Comment by rowlandm** [comment]
@atruskie - which shows that you are under-resourced. Which is another issue that adds to the fun!

**Comment by rowlandm** [comment]
@GerryRyder  - yes I think that is one of the projects Daniel Katz is working on.

**Comment by GerryRyder** [comment]
@rowlandm Yep, Daniel is one of the forces behind Force 11 :-)

**Comment by jklump** [comment]
From the publishers' side, they are now looking to include the [FAIR Data Principles](https://www.force11.org/group/fairgroup/fairprinciples) and the [FORCE11 Software Citation Principles](https://www.force11.org/group/software-citation-implementation-working-group) into the new [COPDESS](http://www.copdess.org/) Statement of Committment. COPDESS is the Coalition for Publishing Data in the Earth and Space Sciences.

**Comment by dylan-jayatilaka** [comment]
Here is our software which we have to develop while doing research simultaneously:

**Comment by dylan-jayatilaka** [comment]
http://crystalexplorer.scb.uwa.edu.au/

**Comment by dylan-jayatilaka** [comment]
It uses free software which is undocumented for user, but code-base is highly documented:
https://github.com/dylan-jayatilaka/tonto

**Comment by MilesMcBain** [comment]
rOpenSci have a Twitter bot that tweets every time one of the R packages in their repository gets cited: https://twitter.com/rocitations
