### ISSUE TITLE
 How can we build the RSE community in AU/NZ?

### ISSUE THREAD

**Issue by manodeep** [rse-aunz/rse-au#30]

**Comment by mingfangwu** [comment]
Nicholas (@njtierney) has put the notes in the issue #39

**Comment by goldingn** [comment]
photo of flipchart from the Vic meetup:
![2018_08_14 16_50 office lens](https://user-images.githubusercontent.com/4450731/46396057-9e6bf400-c731-11e8-86a5-61d1d65a9ede.jpg)
(just for completeness, detailed notes in Nick's post)

**Comment by atruskie** [comment]
Attached is a workshop answer for this question from the QLD F2F (#19):

![img_20181008_094524](https://user-images.githubusercontent.com/1452968/46589216-cfaa4280-caea-11e8-9f98-d4f4827114ef.jpg)

- we need to talk about needs and what can be done
- lack of higher positions in general staff
- what is the RSE-AU group aiming for?
- we should recognise the spectrum of IT <--> Academic researcher
- we need to gather evidence for change later (long-term career pathways)
