### ISSUE TITLE
 How well do "Academic Specialists"-type roles fit with RSEs?

### ISSUE THREAD

**Issue by manodeep** [rse-aunz/rse-au#33]

**Comment by atruskie** [comment]
photo of the question asked at QLD F2F (#19):
![img_20181008_094424](https://user-images.githubusercontent.com/1452968/46588956-b653c700-cae7-11e8-83f4-210a1c8ef167.jpg)

and some translation:
- we chose to interpret the question as "how do our current roles fit with the definition of RSE?"
- 2/4 would not consider themselves academic at all
- 2/4 wrote their own position descriptions, 1/4 actually has a good position description, 1/4 had a boilerplate PD which was chucked as soon as they started
- are RSEs:
  - professional staff? standardised tasks, routine procedures, could be replaced with a new hire
  - academic staff? creative work, non-standard approach, replacing means different work is done
- there is no "Standard RSE"
- RSEs work _with_ researchers, not _for_ them
    - the above definition was not related to whether or not they were physically embedded with the group or not
- not all 3rd space professionals are RSEs, but all RSEs are 3rd space professionals
- previously well-defined professionals don't need RSE label (like sysadmin, or business analyst)
- Would a consulting model work? Like business analysts, IT consultants, management consultants?
- there are implicit assumptions/connotations attached to _**Research** Software Engineer_ that were problematic
- despite all the above, we all agreed there was utility in the RSE label
