### ISSUE TITLE
Should training researchers be part of the RSE job description?

### ISSUE THREAD

**Issue by manodeep** [rse-aunz/rse-au#36]

**Comment by GerryRyder** [comment]
If your role involves training researchers, you might be interested to join an upcoming webinar hosted jointly by ARDC and EMBL.  Titled: "Teaching and training: lessons from education and cognitive science to promote learning" and presented by Dr. Rochelle Tractenberg from Georgetown University, USA, the webinar will run 12.00-1.00pm AEST, Tuesday Aug 21.  Find out more, and register [here](https://register.gotowebinar.com/register/289650237669423619)

**Comment by goldingn** [comment]
photo of flipchart from the Vic meetup:
![2018_08_14 17_01 office lens](https://user-images.githubusercontent.com/4450731/46396164-f0ad1500-c731-11e8-8ff3-414026037cf3.jpg)

**Comment by atruskie** [comment]
Attached is a workshop answer for this question from the QLD F2F (#19):
![img_20181008_094648](https://user-images.githubusercontent.com/1452968/46589234-fec0b400-caea-11e8-94e3-64e74dec46d7.jpg)

- We should be teaching 
    - reproducibility
    - how to navigate open source
    - how to self-diagnose issues
    - frameworks for computational research
- We think RSEs should be a consultancy, not a service (?)

**Comment by atruskie** [comment]
I can't remember/wasn't part of that group. @weaverbel, @amandamiotto, @MilesMcBain, @cofiem: do you have any more to add?

**Comment by rowlandm** [comment]
Training is a hidden cost that RSEs bear for the University. We should flag that in our new website and discuss this at C3DIS workshop.
