### ISSUE TITLE
Open the email group

### ISSUE THREAD

**Issue by jni** [rse-aunz/rse-au#37]
Do we really want the email group to be invite-only? It was off-putting to me, at least.

In other news, my community (image analysis) has recently adopted a unified Discourse forum, which I would consider a fantastic, more full-feature option for this group. See example here:

https://forum.image.sc/

Here is a discussion about how to run discourse as both an online forum and a mailing list:

https://forum.image.sc/t/formal-policy-for-project-to-be-a-software-partner/18834/14

A specific advantage over Google Groups is the use of tags, so that users can subscribe only to specific topics. It's also fully open source so it can be run on our own hardware.

**Comment by jni** [comment]
(or NeCTAR instance)

**Comment by jni** [comment]
Yes, I was saying that requesting access was one step too many. ;) (And yes, I have requested it.) imho you should have to register (to prevent spam), but reading should be open. But maybe I’m missing important reasons for secrecy. =)

**Comment by manodeep** [comment]
Ahh I see what you mean. We are committed towards transparency and open-ness within the community, and that should extend to (at least reading) the exchanges on the mailing list. I will table an agenda item for the next Steering Committee meeting (in two weeks) #38

That example forum/mailing list looks slick -- are you willing/able to set one up for RSEs, if we wanted to go that route?

**Comment by jni** [comment]
I have never set up a discourse instance but I am willing to try. =)

**Comment by rowlandm** [comment]
I think gitter would be another option which is also quite open. Depends
what we want.

**Comment by jni** [comment]
Gitter is more difficult to search / navigate later.

**Comment by atruskie** [comment]
IMO I find both slack and gitter offputting as they benefit from real-time interaction - as IM tools they do this well. Discourse and Google groups match the asynchronicity I'd want to have in this community and they also provide searchable history.

I haven't set up discourse either, but I want to give it a go. My own project is considering setting up a discourse instance.

**Comment by jni** [comment]
@rowlandm that's the easiest, but discourse has benefits above and beyond this:

(1) It's FOSS and controlled by us. I've been bitten enough times by Google (Reader, Notebook, Timeful, and to a lesser extent, Wave) that I dislike relying on their infrastructure. Groups in particular has been neglected for long enough that I am not super-optimistic about its future.
(2) It's prettier. ;)
(3) It has more mod-cons such as tagging and pings for users, which means subscribers can easily customise their notifications and interactions.

**Comment by goldingn** [comment]
I'm also a fan of discourse. The URSSI has one if anyone wants to take a look: https://discuss.urssi.us

It's not too difficult to set up, with e.g. digital ocean hosting: https://www.digitalocean.com/community/tutorials/how-to-use-the-discourse-one-click-application-on-digitalocean

And it might make sense to get a non-gh-pages URL. 

But there are still time and financial costs to setting up and maintaining something like that.

**Comment by rowlandm** [comment]
It would be good if we had two (or three) people willing to maintain it!

**Comment by jni** [comment]
>   - Is there free hosting for Discourse?

Not that I'm aware of. But a self-maintained instance is free.

>   - If you set it up but have to leave the RSE community - who will
   maintain it?

As @rowlandm, we would need buy in from more than just me for this question to have a satisfactory answer, but it's looking promising based on this thread.

>   - Who will look after the backups and maintain the security patches?

I haven't looked into this in detail, but both things appear to be single-click features of the discourse software.

   - Will we migrate the old messages from the Google Groups?

Dunno. Only very few people have seen those messages though... ;) More seriously, again, I haven't looked into this in detail but I would like to know if

**Comment by jni** [comment]
I also want to clarify that I may *sound* like I'm pushing super hard for Discourse. I'm not, it's a gentle suggestion, I'm a newcomer to this community and more established members should weigh the pros and cons. The only thing I'm pushing hard for is a publicly-visible, easy-to-join forum.

**Comment by rowlandm** [comment]
No worries. I also don't want to block your enthusiasm!

**Comment by rowlandm** [comment]
HI @jni  - could you also potentially look at the implications of using Discourse vs opening the Google groups?

Would that be possible?

**Comment by jni** [comment]
@rowlandm what do you mean exactly? Here are the pros/cons of Google vs Discourse as I see them.

- Opening Google is pretty much instantaneous and effortless, while setting up Discourse will probably require at least 1 day of effort by someone, plus some ongoing maintenance
- Discourse will also require hosting, which means at a minimum periodically justifying our existence to NeCTAR. Should be fine I think.
- Discourse is a more modern interface (I like it better at least), fully open source, which gives us more control both now and in the future. 

In the short term I can't do the Discourse setup but around end November I should be able to spend a day on it if we get a consensus that that's what we want.

**Comment by rowlandm** [comment]
OK - Thanks.

I think we should open Google for now, less work. As Kerri mentioned earlier, we do need to be mindful of privacy concerns.

Maybe @mingfangwu @manodeep we should email this to the overall group and set a date for changeover, with any dissenting voices to pipe up any concerns they may have as individuals?

**Comment by rowlandm** [comment]
I just saw this....

https://github.com/discourse/discourse_docker
