### ISSUE TITLE
2018-08-28 Interim Steering Committee Meeting

### ISSUE THREAD

**Issue by manodeep** [rse-aunz/rse-au#38]
Aug 28, 2018 at 2 pm

Agenda:

- Finalize the questions to appear on the AUS international survey [questions](https://github.com/rse-aunz/international-survey/blob/2018-survey/survey_creation/2018/questions.csv)
- Open up the googlegroups to be readable without having to sign-in

**Comment by kerriwait** [comment]
- Discuss workshop and BoF at eResearch 2018 planning

**Comment by manodeep** [comment]
I think @kerriwait's point about letting people know that we are opening up the googlegroups is important. People on the list should have the option of leaving, if they so choose, if they are not comfortable with participating on an open mailing list.
