### ISSUE TITLE
Notes from the "Community" break out session from the Vic Meeting 15th August 2018

### ISSUE THREAD

**Issue by njtierney** [rse-aunz/rse-au#39]
Hi Everyone!

Here are the notes I made last week at the victoria RSE meeting, from the break out group on "Community".

# Community in Research Software

- The community needs to be established early as a safe, inviting space
- The community should meet face to face, ideally in a small ish group (40-60), for a few days, to discuss ideas.
- We could create a directory of contacts (which could be public/private facing), which would provide a way for people to find others with skill sets they would like to work with.
- Events we could run include unconference type events, such as the rOpenSci unconference - See the [USA unconf in 2018](http://unconf18.ropensci.org/) and the [Australian ozunconf in 2017](http://ozunconf17.ropensci.org/).
- Another event could be a grant application evening event, where people work together to create a grant application in an evening, and then pitch the idea at the end of the night. A winner is announced by vote, and they win a small monetary prize

# What do we want out of the community?

- A space to get help
- A place for support

# Other ideas

- A full-time community manager would very valuable
- mediums for communication: Slack, Twitter, Discuss forum

**Comment by rowlandm** [comment]
Nice work Nicholas.

I will be happy to try and form a Unimelb RSE community with this in mind.
I will be catching up with Nick Golding next week to talk more about it.

Anyone who wants to help form a Unimelb RSE community can contact me at
rowland.mosbergen@unimelb.edu.au
