### ISSUE TITLE
Feedback on Australian survey

### ISSUE THREAD

**Issue by manodeep** [rse-aunz/rse-au#40]
Deadline to finalize is end of the week. Survey url is deliberately not listed here.

**Comment by manodeep** [comment]
@amandamiotto Do you mean something like a drop-down? Not sure that is possible

(I personally don't like this 1-10 rating because there is no information that states how that scale relates to the actual numeric values. Perhaps it's a logarithmic scale; I would prefer the question to specify ranges in terms of percentages -- 0-10%, 11-20%, 21-30%...etc)

**Comment by amandamiotto** [comment]
I can't see the link now, but I felt like I remember it was in limesurvey? You can do arrays: https://manual.limesurvey.org/Question_types#Array_.28Texts.29

**Comment by manodeep** [comment]
Yeah I can't access the survey either. @Oliph might know

**Comment by smoskwa** [comment]
I'm trying to figure out how to best adapt this for RSEs who are not employed at a university

If I just stick with the publicly funded research agencies ("PFRAs") I think the main ones to cover are CSIRO, Geoscience Australia, Defense Science & Technolgy, Bureau of Met, ANSTO

These, and government department workers are covered by type_organisation=government but it would be nice to have a follow up questions (similar to university) to identify the specific institution

I'll add countries/aus/levels_govt.csv which will need to include APS/EL/SES levels but also the different scales found at CSIRO, DST, ANSTO. 

Then I'll add another option to socio11ausnzl so people can select from that.

Any other PFRA-specific changes I should look at?

**Comment by smoskwa** [comment]
okay I made a quick PR with a subset of AUS government levels (APS+CSIRO, it turns out BoM, GA, DST all use the same labels even if they have unique enterprise agreements and inconsistent salary ranges)

https://github.com/softwaresaved/international-survey/pull/222

**Comment by manodeep** [comment]
@nooriyahp Do you know if the levels are the same for NZ? And/or if you would like this question to be shown for the NZ survey?

**Comment by smoskwa** [comment]
I wasnt confident enough in what I found in a few minutes googling to include specific options for ANSTO or NZ-based government agencies however there is always the "other" option (so it doesnt hurt to show the question to NZ RSEs and someone might jump in with their own PR)

**Comment by mingfangwu** [comment]
**Front page:** 
1. Please note that this research -> Please note that this **survey**
2.  but there is a significant benefit to the research community -  but there is a significant benefit to the community of **research software engineers** 
3. You can remove your data from our records after completing the survey. ??? Does this mean: Even you have completed the survey, you can still withdraw your survey from survey analysis by informing us to remove your survey data. 
4. We do not collect personal data in this survey -> We do not collect personal data in this survey. When you fill in survey, please also be mindful not to include any information that could identify you. 
5. Who is responsible for this survey.  The RSE-au is instrumenting this survey, should RSE-au bear any responsibility? 

**Questions about you:**
Q1: Is this survey countrised to Australia and New Zealand only? If yes, can these two countries brought on top of the country selection?
After Q2, the number jumps to Q10, then to Q19, the numbering is not right. 
Q22  No answer: What does it mean, don't want to answer, N/A?  Also I am having trouble to see what I select, then figure out it is the dark green is the selected one. 
Q43 & Q50 & Q52 & Q53: Some combinations of these questions may give away personal information if not many people hold the same position from a university. The front page should make it clear that we will try best to remove any information (or combination of information that may identify you).

**Your employment history**
Q70: Should choices include "others"

**Your working practice:**
Q73:  A software engineer may not work with the same research, but almost the same research group. 
Q76 would go with Q87. If the answer to Q76 is NO, then Q87 is not valid. 
Q89: Do you have an ORCID? Should be options include: No, I don't know ORCID at all,  No, I know ORCID system but think no point for me to get ORCID (something along those lines?)
Q92: software development related training? (university may provide other training to RSEs).  Does this mean workplace supported training? Some people may pay themselves for a professional training. 
Q94: I don't understand how some choices are related to the question, e.g. Books&merchandise, Advertising&sponsorships, etc.  SaaS (Software as a Service) need to be expanded. 

**Demographic questions**
Q102 and Q123 are the same. Does Q122 suppose to be "What is your university pay-level?"

**Final questions about you**
Q124: UK RSE -> Aus RSE??  (do we include NZ?)
Q131: what does this mean?

**Issues across all pages**
Numbering of questions
There is no "back" button to see answers put in previous pages.

**Comment by mingfangwu** [comment]
@Oliph Thanks for fixing the issues I raised. 

For the question: Which universities do you work for? Should the second last choice "Othe" from the drop down list be removed?
