### ISSUE TITLE
Suggestion to agenda of the RSE workshop and BoF at the eResearch conference

### ISSUE THREAD

**Issue by mingfangwu** [rse-aunz/rse-au#41]
[The RSE workshop proposal](https://conference.eresearch.edu.au/2018/07/workshop-for-rses-recognition-and-career-development-for-researchers-who-code/)
[The RSE BoF proposal](https://conference.eresearch.edu.au/2018/08/bof-for-rses-recognition-and-career-development-for-researchers-who-code/)

**Comment by rowlandm** [comment]
Sorry I wasn't there today. happy to setup another time to discuss what needs to be done.

**Comment by nrmay** [comment]
My brief notes from RSE Steering Committee Meeting (2018-08-28);

- Workshop Goals:
  - 1st Year focus - Setting up RSE Assocs (National & Institutional)?
  - Future Years focus - combine community building and technical talks.
  - could include an open call for nominations to the new steering committee.
     - Do we elect the first committee at the workshop or after?

- Lightning Talks:
  - a set format - e.g. Rezbaz intros (4 questions) 
  - career paths of selected attendees. (appox 10 x 6mins, with someone standing by the gong/plug)
  - need to highlight some issues/problems

- Brainstorming:
  - how can an RSEA help with the issues/problems identified above
  - need a framework to aggregate the issues/problems.
  - provide some prepared in advance

- Actions:
  - there should be some ideas for attendees to action after the event.

- BoF: (40 mins)
  - Provide a report on the workshop for the general audience.
  - Especially promote the Actions.

**Comment by rowlandm** [comment]
Extra notes from #38 

Discuss with Michelle who should be invited to give a "keynote" talk, who could give a lightning talk
Ask Sam 2-3 weeks before the event about a list of people who register to the workshop, contact people if they are willing to give a lightning talk about their experience, challenge and success story of being a RSE.
The workshop should set up goals about what we want to get out from the workshop and actions to follow on after the workshop.
The 40 minutes BoF session could be used to report back what come out of the workshop
The workshop and the BoF organiser to have a meeting to plan the workshop and put the proposed plan for the next steering committee meeting. Members are encouraged to get their suggestions in to the #41 .
There should be a regular (annually or every half a year) RSE workshop/conference for community building

**Comment by amandamiotto** [comment]
career paths of selected attendees. (appox 10 x 6mins, with someone standing by the gong/plug)
I'm happy to be one of the people to give a lightning talk on my career path (BioInfo-> SoftDev-> Generalist)

**Comment by rowlandm** [comment]
- First session: Why are we here?
- How do we keep our core group / how can we keep the momentum going?

**Comment by rowlandm** [comment]
- Find out actions, before asking for volunteers

**Comment by rowlandm** [comment]
https://conference.eresearch.edu.au/2018/07/workshop-for-rses-recognition-and-career-development-for-researchers-who-code/

**Comment by mingfangwu** [comment]
Based on yesterday's tel-call, I draft this[ running sheet](https://docs.google.com/document/d/1EqGofM0-Uev0MSg1Fzm75J8UKWrwz516jl7dpt0BFWY/edit#) for the RSE workshop at the 2018 eRA. Please feel free to comment.

**Comment by rowlandm** [comment]
Thanks Mingfang!
