### ISSUE TITLE
For Review: RSE-AUS 1 page slide

### ISSUE THREAD

**Issue by nrmay** [rse-aunz/rse-au#42]
We've been invited to present a lightning talk during the International Session at RSE-2018.
This will be for 2 minutes and 1 slide.
Find a draft of the slide via this link: [RSE-AUS-1-Page-2018.pdf](https://github.com/rse-aunz/rse-au/files/2330513/RSE-AUS-1-Page-2018.pdf)

Any comments or suggestions would be most appreciated.

**Comment by manodeep** [comment]
I would include a comment that we are participating in the survey.

**Comment by manodeep** [comment]
@nrmay Do you know if anyone from NZ is presenting?

**Comment by nrmay** [comment]
I don't know. But given the severe time restriction, I thought covering AUS efforts was sufficient.

**Comment by nrmay** [comment]
Added:

- we are participating in the survey.
- https://rse-aunz.github.io/ as link.

**Comment by nrmay** [comment]
version 2 ... [RSE-AUS-1-Page-2018-v2.pdf](https://github.com/rse-aunz/rse-au/files/2330732/RSE-AUS-1-Page-2018-v2.pdf)
