### ISSUE TITLE
stickers!

### ISSUE THREAD

**Issue by goldingn** [rse-aunz/rse-au#43]
Belinda mentioned that we need an RSE Au/NZ sticker for advertising, and I couldn't agree more!

Anyone feeling artistic?

Also, do people prefer [hex](http://hexb.in/) or non-standard shaped stickers?

**Comment by manodeep** [comment]
I totally second this! Completely devoid of any artistic skills though. 

Should we consider posting to 99 designs (https://99designs.com.au/) for an RSE AU logo?
