### ISSUE TITLE
2018-09-25 Interim Steering Committee Meeting

### ISSUE THREAD

**Issue by manodeep** [rse-aunz/rse-au#44]
I am adding two items that will be relevant to discuss. This will also be the last intermin steering committee meeting before eRA. 

Agenda:

- Update on the 1-day workshop and BoF at eRA
- Updates on the QLD F2F planning (if any)

**Comment by mingfangwu** [comment]
I have drafted this[ running sheet](https://docs.google.com/document/d/1EqGofM0-Uev0MSg1Fzm75J8UKWrwz516jl7dpt0BFWY/edit#) for the RSE workshop at the 2018 eRA. Please feel free to comment.

**Comment by goldingn** [comment]
What time is the call & is there a zoom link yet?

**Comment by mingfangwu** [comment]
@goldingn It is 2-3pm.  I am about to update calendar invite. You should receive one now.

**Comment by manodeep** [comment]
@mingfangwu Since the google docs link for the running sheet is publicly posted here, I updated the sharing so that anyone with link can comment, rather than edit.

**Comment by manodeep** [comment]
Attendees: Nick Golding, Manodeep Sinha, Nicholas May, Kerri Wait, Sam Moskwa, Anthony Truskinger, Valerie Maxville, Lance Wilson

Action items:

For the 1-day workshop, the running sheet needs to be updated to contain
- A deliverable for each session
- Invited speaker for the introductions
- Confirmed list of speakers from the registrations
- Collaborative environment for creating the "white paper" 

Other action items:
- Touching base with other workshop organizers (Valerie is contacting `Collaborative Research`, Kerri and Lance to contact `System Admins`, someone else for `MyTardis` organizers?)
- @manodeep to send around email with a reminder for the 1-day workshop, including a snippet saying limited financial assistance is available for registrations
