### ISSUE TITLE
Raising awareness at universities and the role of PhD students

### ISSUE THREAD

**Issue by mohamed82008** [rse-aunz/rse-au#45]
Hi,

I am a PhD student at UNSW Canberra. I am somewhat involved in FOSS mostly using [Julia](https://julialang.org/) and I am interested in this whole RSE movement. So I wonder if and how I can be part of it and more importantly how it can benefit from me and how I can benefit from it. In the long run, I do consider a possible career path as a Julia RSE so I can see the benefit of RSEs getting more recognition and becoming an integral part of the research process at universities. I was introduced to RSEs through this [JuliaCon talk on Youtube](https://www.youtube.com/watch?v=8ZSaAM8hhJ4) and I believe more of these talks are necessary to raise awareness in Australian universities of the importance and success stories of RSEs.

I believe one main part of the problem here is that a number of professors only believe in the value of papers and research contribution, not so much in the value of realizing those research contributions in the form of useful software, paving the road for more research using those software. These days there seems to be more journals like the [Journal of Open Source Software (JOSS)](https://joss.theoj.org/) and [Advances in Engineering in Software](https://www.journals.elsevier.com/advances-in-engineering-software) which seem to bridge this gap between traditional research and software contributions, but I feel more awareness is necessary to let university admins in on this trend through the sharing of success stories and why it is important. In particular, in the Julia community some of the best written packages are written by researchers and PhD students. In fact, the whole of Julia started as the PhD project of [Jeff Bezanson](https://github.com/JeffBezanson/) and some of his mates. So the convergence of research and research software is very evident in the Julia community which is awesome.

I may be thinking bigger than I can do at this point since I am a mostly powerless (policy-wise) PhD student now who contributes to FOSS, but I would love to see an awareness talk delivered at my university where I can show my support. Having a Discourse page can also help connect and bring people together. I find the [Julia Discourse page](https://discourse.julialang.org/) for instance a great place to hang out. Please let me know if and how I can be involved. Being a student, I am low on funds so my commuting power is limited but I can help arrange or coordinate local talks and meetups. I think it would help to have some representatives from every university that can get some promotion message through the university's newsletters and media channels so I don't mind being that guy at my campus. I am not sure how people here will receive this RSE trend, but I am, as I am sure we all are, hoping for the best.

Cheers,
Mohamed

**Comment by smoskwa** [comment]
Hi Mohamed,

You make some great points so hopefully I’m not hijacking the thread by responding more broadly about careers in eResearch as a whole.

For the RSE movement to succeed it absolutely need to be inclusive of students.

Funding for travel and accommodation is a significant obstacle to participation by students and early career researchers. As it happens I’ve put together an  “AeRO Scholarship Fund” to support attendance at eResearch events (and not just the ones AeRO runs). The plan was to announce it next month and start operating in 2019. Of course most universities already offer financial assistance programs with far more funds than AeRO can attract so perhaps we just need to maintain a list of those that are available (and cover RSE events) in an easily digestible format?

However inclusion is more than just having the ability to attend events, we need to be inviting student to speak and contribute- and I don’t just mean through poster sessions and lightning talks. As a conference organiser its very hard for me to look out across the university sector and know which students to approach. So I wonder if a good model might be a student-run RSE organisation with an annual symposium (the closest thing that comes to mind is the bioinformatics one https://combine.org.au/). That would provide a forum for students to develop ideas and elect representatives. Then people like myself would have a place to go to involve students in specific conferences, etc.

I’ve also partnered with ribit.net to host speed networking events where students can speak to potential eResearch employers. A number of the students attending are likely to go on to careers as RSEs. Perhaps there is an opporunity to be asking specific questions.

It's unclear to me how to find volunteers (such as yourself) at each and every uni and to have a succession plan as students inevitably move on. So I'd be interested in hearing about existing bodies/associations that span universities and can reach into the many different newsletters and communication channels.

regards,
Sam

**Comment by squarcleconsulting** [comment]
Sam / Mohamed / others interested in Postgrad Students issues,

Council of Australian Postgraduate Associations Incorporated
http://www.capa.edu.au/

Australian Council of Gradate Research (aka DDOGS, Deans and Directors of Graduate Studies)
https://www.ddogs.edu.au/

Department of Education release of the Research Training Implement Plan:
https://docs.education.gov.au/system/files/doc/other/implementationplan.pdf 

Cheers,
Paul

**Comment by mohamed82008** [comment]
@smoskwa thanks for your response. These are nice ideas. I would love to be part of that student-centered organization if it sees the light.

@squarcleconsulting thanks for those links, I will keep an eye for anything relevant there.

**Comment by amandamiotto** [comment]
Dear Mohamed


Check out your local hacky hour too who may be able to get you involved and connected with local groups https://research.unsw.edu.au/events/hacky-hour. You've mentioned you're already in touch with your local meetups which is fantastic- they are a great way to network and become comfortable with presenting as well. Check out if there's a toastmasters group as well, which is a group that can help you practice to present. Offer to present at your local Research Bazaar conference as well.


There is always Software Carpentry as well-  you could look at if there's interest to write a Julia class aimed for academics? https://software-carpentry.org/lessons/ . If you want to make it discipline specific, look at data carpentry which is also run by the carpentries group. https://datacarpentry.org/lessons/


Amanda Miotto | Senior eResearch Analyst


eResearch Services- Office of Digital Solutions

Griffith University/ QCIF | Nathan | QLD 4111

T +61 7 373 54697 | @amandamiottoGU |

 a.miotto@griffith.edu.au

Hacky Hour: Griffith.edu.au/hackyhour | @hackyhourGU



Griffith University - CRICOS Provider Number 00233E


PRIVILEGED - PRIVATE AND CONFIDENTIAL

This email and any files transmitted with it are intended solely for the use of the addressee(s) and may contain information which is confidential or privileged. If you receive this email and you are not the addressee or responsible for delivery of the email to the addressee(s), please disregard the contents of the email, delete the mail and notify the author immediately.


________________________________

**Comment by mohamed82008** [comment]
@amandamiotto  Thanks for the links. I was planning to give a Julia workshop/class on campus at some point and these seem helpful. Thanks.

**Comment by rowlandm** [comment]
@mingfangwu - would it be possible to do a RSE tech talk early next year?
