### ISSUE TITLE
Minutes from the Montly Meeting (2018-09-25)

### ISSUE THREAD

**Issue by nrmay** [rse-aunz/rse-au#46]
### Planning for the eResAU18 RSE Workshop.

- Only 17 people have signed up to date. This may be due to cost, clashes with other workshops, etc.
- Possible solutions to increase participation include: 
  - Provide a limited number of 'free' passes to students.
  - Provide a means for people to contribute in advance of the workshop.
  - Provide a means to collaborate online during the workshop.

- There was agreement that we need to put more detail into the workshop schedule, including:
  - More description about sessions.
  - Session deliverables.
  - Speakers.
  - Session MCs.
  - etc.

- Please, add your comments in the following document: 
[Workshop for RSEs: Recognition and Career Development for Researchers who Code](https://docs.google.com/document/d/1EqGofM0-Uev0MSg1Fzm75J8UKWrwz516jl7dpt0BFWY/)

### The eResAU18 RSE BoF Session.

- Proposal to use this session to share the proceedings from the workshop with a wider audience, including:
  - An overview of the RSE context.
  - Deliverables from the workshop.
  - Open the call for nominations for Steering Committee.

### Action items:
 
   1. Finalize a list of speakers. (Mon. 1st Oct.)
   2. Finalise the session MCs.  (Mon. 1st Oct.)
   3. Finalize the Workshop Schedule. (Tue. 2nd Oct.)
   4. Agree on the collaboration tools for the workshop. (Tue. 2nd Oct.) - Nick May
   5. Advertise the workshop more widely. (Wed. 3rd Oct.)

---

**Comment by nrmay** [comment]
I'll take ownership of the action Item (iv.) Agree on the collaboration tools for the workshop.

**Comment by rowlandm** [comment]
I can be the MC for the first and last sessions if Georgina doesn't want to.
