### ISSUE TITLE
Minutes from the Monthly Meeting (2018-11-26)

### ISSUE THREAD

**Issue by mingfangwu** [rse-aunz/rse-au#50]
Agenda:

- Bio IT meeting at ABACBS (https://www.abacbs.org/conference2018/about/)
- NSW f2f meeting
- RSE presence at Monthly TechTalk 2018 (https://www.meetup.com/monthlytechtalk/)

Minutes from the last meeting: https://github.com/rse-aunz/rse-au/issues/47

**Comment by rowlandm** [comment]
Also updated website.

**Comment by rowlandm** [comment]
Two focuses - sustainable community and advocacy

We could also work on a discipline level approach ASA day for software, Bioinformatics Bio IT meeting

Can we provide info to the RSE community to help them sell their case? Like a manifesto and store on the website. THe manifesto would be providing what we need to do and also have an appendix of advocates in the AU/NZ community.

We should do the Tech talk. Perhaps have a speaker talking about why you should joing the community (to join the dots), talk about the survey and talk about the future (manifesto)

Also think about running workshops at C3DIS, connect with NCI and Pawsey.

Think about running locations at sites (like tech talk) for the C3DIS, NZ eresearch.

Also think about re-using EMBL-ABR multi-site training for bioinformatics pipeline discussions.

**Comment by rowlandm** [comment]
I say yes. @manodeep ? last chance to backout!

**Comment by manodeep** [comment]
@rowlandm As long as we can identify the 3 speakers associated with each of those three topics, we should lock it in. @mingfangwu Is the tech talk an in-person talk or zoom/webinar?

**Comment by mingfangwu** [comment]
@manodeep TechTalk is both in-person and virtual. We have about 8 locations in major cities for people to go to, also give meeting link to those who aren't able to travel to a location. (Here is the link to the TechTalk: https://www.meetup.com/monthlytechtalk/about/)

@rowlandm and @manodeep Would a talk on "best practice for software in research" fit into the RSE techtalk session? ARDC may have a visitor from US who can talk on this topic. (although I haven't checked his availability on this day/time).

**Comment by rowlandm** [comment]
No - you don't need to be at a particular location. We had a speaker from CERN once who was in Europe. They just zoom into the meeting and share their screen.

**Comment by mingfangwu** [comment]
@rowlandm is right, speakers can be anywhere with an internet connection,  we had 4 speakers from US who presented in the last Nov's TechTalk. 

@manodeep I will check if the person then (from US) is available to give 10-15 minutes talk of the topic. 

TechTalk is on the first Friday every month, so the February is on the 1st.

**Comment by rowlandm** [comment]
How about March? Is that free?

**Comment by rowlandm** [comment]
Feb it is then!

**Comment by manodeep** [comment]
@rowlandm Yes. Let's lock that in

**Comment by rowlandm** [comment]
Manifesto could include:
- Who to work with eg. AAL, ARDC, BPA, PCI at UniMelb
- include domain specific information
- suggest an RSE community manager position
- suggest the setup of RSE fellows

**Comment by rowlandm** [comment]
Also suggestion:
RSE representative per domain, not just per state.
