### ISSUE TITLE
Notes from RSE Perth meeting

### ISSUE THREAD

**Issue by rowlandm** [rse-aunz/rse-au#52]
Attendees:
- Kathryn Barker ARDC
- Grahame Boland CCG (software biosciences domain)
- Krupali CCG (software)
- Catherine (sp?) data scientist at Curtin

Most people from CCG have an industry focus and there is a learning curve.
Talked about data curation at scale and suggested Stemformatics as an example to check out.

ACTION: RM to send KB slides from January 2018 talk at ARDC skills team
ACTION: Try to catchup with ARDC skills team in new year.

**Comment by manodeep** [comment]
Thanks @rowlandm
