### ISSUE TITLE
New member introductions

### ISSUE THREAD

**Issue by zaherj** [rse-aunz/rse-au#54]
Hi,

I couldn't find a thread for new members to introduce themselves, so I created it.

I came across this community the other day. It feels good to know there are other people like me in the world. I felt I really belong here.

I have been working for almost 5 years as software engineer at unimelb supporting research and I can very much relate to all the issues this community is raising.

Are you guys still having monthly meetings? I can see last monthly meeting was end of last year.

Regards

Zaher.

**Comment by atruskie** [comment]
G'day @zaherj,

Welcome to the community! There are many of us spread out all over 🙂

There's a Google Group that has a wider reach and it's also a good place to introduce yourself.  If you haven't already, you can check it out here https://groups.google.com/forum/?#!forum/rse-nz-au

There was a face to face meeting in Melbourne back in August (see https://github.com/rse-aunz/rse-au/issues/21), and a workshop at eResearch Australia (https://github.com/rse-aunz/rse-au/issues/49).

The monthly interim steering meetings are Zoom video calls. We've skipped the last two for various reasons. The next time there is a steering meeting the notes should be posted here in GitHub.

Cheers,
Anthony

**Comment by rowlandm** [comment]
The next meeting is the 26th of February at 2pm Melbourne time.

You can access the meeting here:
https://monash.zoom.us/j/691412731
