### ISSUE TITLE
Agenda for the Monthly Meeting (2019-02-26)

### ISSUE THREAD

**Issue by rowlandm** [rse-aunz/rse-au#55]
Hi All,

The monthly meeting is on at 2pm AEDST on Tuesday the 26th of February. It is held on the fourth Tuesday of the month.

The Zoom meeting is: https://monash.zoom.us/j/691412731

Here is a draft agenda - please add comments if there are other things you would like to talk about (time permitting):

Acknowledgement (from UniMelb): I acknowledge the Wurundjeri people of the Kulin nation as the custodians of the land on which I work, live, and raise my family. I pay my respects to their elders past, present and future. 

1. Feb 8 Tech Talk feedback
2. Discussion on ‘Nominating for committee positions: requirements and process’. [RSE-AUNZ-Poll-Committee-Positions.pdf](https://github.com/rse-aunz/rse-au/files/2890900/RSE-AUNZ-Poll-Committee-Positions.pdf)
3. Deliverables for 2019 https://github.com/rse-aunz/rse-au/issues/51#issuecomment-464959849
4. C3DIS expressions of interest are now open http://www.c3dis.com/presentations
5. Auda Eltahla - Microsoft Research Engagement Manager
5. Request from Jonah of the Carpentries + highlighting the training aspect of RSEs
6. Web and email community engagement

**Comment by rowlandm** [comment]
For RSEs around Parkville in Melbourne, I have booked a meeting room with Zoom at 187 Grattan St on the ground floor in the Boardroom.

**Comment by manodeep** [comment]
We should add a recap of the meeting with Auda Eltahla, the new Microsoft Research Engagement Manager, to the agenda

**Comment by manodeep** [comment]
And thanks @rowlandm for setting this up in the first place

**Comment by rowlandm** [comment]
Oh yeah! Thanks for remembering Manodeep!

**Comment by rowlandm** [comment]
RSE:
Difficult as no zoom chat.
Tangential Ariane.
Software engineering best practices.
Feb is good to have Tech Talk.
Not techncial enough.

**Comment by atruskie** [comment]
To write down my spoken comment on the tech talk:

- Arianne's talk was great( and technical) but it seemed tangential to the goal of advertising/explaining what an RSE is.
- I heard that the youtube link is up for the tech talk. It'd be great to see that advertised? Did anyone post it to the RSE Google Group? I may not have noticed it/missed it...

**Comment by rowlandm** [comment]
2. Commitment, nomination process, voting process.

Commitment? 2-3 hours per week.
Meeting weekly and doing stuff in those meetings.

Gerry and community building eg. face to face meetings. Secretariat. Web presence

Sam - same as ARDC.

Nomination process? Email around community and language is inclusive.Add as a post to the website.
Profiles around the nomination process. More research on how to do this.

Voting process? Open it up for voting.

**Comment by rowlandm** [comment]
Deliverables 2019.
Annual meeting. C3DIS at the end of the meeting.

Meetups.

**Comment by rowlandm** [comment]
4. C3DIS 6th to 10th of May. Data Science Week - NCI and Pawsey in that week.

Co-ordinate in the same week. Look at Data Science of Week.

Paragraph of text. 1/2 day, full day. Cost recovery $250 for full day workshop. Sponsorship. Take it to ANU.

ARDC put in a proposal for a 1/2 day around software curation.

 Georgie - lots of RSEs from public organisations.

Marketing, personas and profiles. Raise awareness.

Re-use the Aero funding model.

**Comment by rowlandm** [comment]
5. Microsoft person.

Regional.

Training as being a separate skill.

**Comment by rowlandm** [comment]
6. Jonah Duckles.

Yes, we can get him to talk at next month's meeting.

**Comment by rowlandm** [comment]
7. We will need to ensure that job emails aren't the main emails around the Google groups email.

Last website update was in November.

**Comment by manodeep** [comment]
For the RSE manifesto, I noted this related manifesto on the chat window: https://codeisscience.github.io/manifesto/
The manifesto is here: https://codeisscience.github.io/manifesto/manifesto.html

For workshop funding, sadly none of the funding opportunities from the Academy are relevant to the RSE cause (without being exclusionary to some discipline)

**Comment by nrmay** [comment]
Re: Acknowledgement of Country.

Since we are spread out, it may not be appropriate to acknowledge specific groups. I suggest that we use a broad statement, such as:

> We acknowledge the Traditional Owners of country throughout Australia and recognise their continuing connection to land, waters and culture. We pay our respects to their Elders past, present and emerging.

From the following: https://www.commonground.org.au/learn/acknowledgement-of-country

What about New Zealand? Is there a similar tradition?

**Comment by rowlandm** [comment]
Good point.  I will change it. Thanks Nick

Regards,

Rowland
_______________

Rowland Mosbergen
Petascale Campus Initiative - Facilitator

The University of Melbourne, Victoria 3010 Australia

E:  rowland.mosbergen@unimelb.edu.au

M: +61 3 834 46623


I acknowledge the Wurundjeri people of the Kulin nation as the custodians
of the land on which I work, live, and raise my family. I pay my respects
to their elders past, present and future.
