### ISSUE TITLE
C3DIS 2019 Workshop Submission

### ISSUE THREAD

**Issue by rowlandm** [rse-aunz/rse-au#56]
As per the Meeting in February:
https://github.com/rse-aunz/rse-au/issues/55

C3DIS sumbissions are open but close Marcfh 1st. 

Here is the 250 word abstract:
https://docs.google.com/document/d/1tfvmcNQEe7jallqfWhpQ5szw305E_H5Pc21Qgy9ooRQ/edit?usp=sharing

**Comment by rowlandm** [comment]
As per the Meeting notes:

1. C3DIS 6th to 10th of May. Data Science Week - NCI and Pawsey in that week.

Co-ordinate in the same week. Look at Data Science of Week.

Paragraph of text. 1/2 day, full day. Cost recovery $250 for full day workshop. Sponsorship. Take it to ANU.

ARDC put in a proposal for a 1/2 day around software curation.

Georgie - lots of RSEs from public organisations.

Marketing, personas and profiles. Raise awareness.

Re-use the Aero funding model.

**Comment by rowlandm** [comment]
NOTE: Currently leaving this as one author, will be updated in the final abstract submission. Rowland will send this off at 12pm AEDST on the 1st of March 2019. All comments welcome!

**Comment by manodeep** [comment]
Did we learn if the deadline is possibly Mar 8th?

**Comment by rowlandm** [comment]
Seems to be 1st March.

Regards,


Rowland

_______________



*Rowland Mosbergen *

Petascale Campus Initiative - Facilitator

The University of Melbourne, Victoria 3010 Australia

*E:  *rowland.mosbergen@unimelb.edu.au
*M: *+61 3 834 46623

I acknowledge the Wurundjeri people of the Kulin nation as the custodians
of the land on which I work, live, and raise my family. I pay my respects
to their elders past, present and future.

**Comment by smoskwa** [comment]
yes March 1st
(sorry about the confusion I was thinking of the time frame for reviewing submissions)
