### ISSUE TITLE
Nomination and voting process for a new steering committee

### ISSUE THREAD

**Issue by rowlandm** [rse-aunz/rse-au#57]
Hi All,

The agreement from the interim steering committee was the following structure:
- Chair (x1)
- Secretary (x1)
- General Members (x6, one for each deliverable)

I wanted to ask for comments around the nomination process in this thread.

Based on what I have heard so far, I would suggest the following:

1) Email the entire community a nomination workflow for 1 week to give the community an opportunity to provide feedback. 
2) Refine the nomination workflow after submissions have closed, and have at least 5 members of the interim steering committee approve it, with only one person per organisation in those 5 (eg. two people from UniMelb cannot make up the quorum). This should be done within a week.
3) Email the entire community the finalised workflow and ask for nominations. The closing date for nominations should be 22nd of March.
4) Voting should be from the 27th of March to the 30th of March.
5) Votes should be tallied by the independent person who organised the process and shared on the 31st of March.

Things to agree on: 
- Whoever is running this process cannot apply for secretary or chair to keep things as independent as possible.
- Do we want to structure diversity into our 6 general members? eg. ECR, Regional etc.

Here are the cleaned up notes from the previous monthly meeting in Feb 2019 #55 :
- Commitment? 2-3 hours per week.
- Meeting weekly and doing work in those meetings.
- Gerry mentioned ARDC could help with community building eg. face to face meetings and secretary positions. They could also help with a web presence.
- Sam from AeRO mentioned that they could do similar things to the ARDC.
- What is the nomination process? We should email around community and ensure the language is inclusive. Also add as a post to the website.
- There should be profiles around the nomination process. 
- We should do a little more research on how to do this, especially around the Carpentries.

**Comment by goldingn** [comment]
Sounds good!

I think it makes sense to have the organiser not go up for secretary or chair.

Despite suggesting it, I'm now not sure about stratifying positions by categories for diversity in this first round. With a relatively small pool of nominations and a small committee, I think it will be too restrictive - it'll be very hard to find a committee of engaged people that covers all those factors, _and_ across separate positions. Though I am worried about bias, particularly gender bias at this stage.

An alternative could be to enforce a minimum number of (e.g.) non-male positions on the committee, fill those first and then fill the remainder of the positions. It might be best to do this with a preferential voting system to get more information from the potentially small pool of voters.

**Comment by goldingn** [comment]
Also, I have taken part in anonymous online votes before where each voter is emailed a unique code so that only they can vote, they can vote only once, and votes are anonymous. That seems like it would be sensible here.

There are probably several free web services to do that, but here's one: https://www.adoodle.org/

Does anyone have comments on these systems, or another preferred platform? If that sounds sensible, I can do some test runs to see if this or other platforms meet our needs.

**Comment by rowlandm** [comment]
I like the idea of maybe 2 positions being diversity positions to ensure
there is at least some opportunity, plus enforce a minimum number of
non-male positions. If there aren't enough votes, then maybe the chair can
finalise those diversity selections?

I'm happy to have anonymous votes too. Although I worry due to the low
voter turnout there are opportunities of having unintended biases from
active organisations... If that makes sense...

**Comment by rowlandm** [comment]
Draft email notification is here:
https://docs.google.com/document/d/1LCROJHk1UMnve2_Ug97DwbHbjEox3qM8U1unph9XKbk/edit
