### ISSUE TITLE
 Agenda for the Monthly Meeting (2019-03-25)

### ISSUE THREAD

**Issue by manodeep** [rse-aunz/rse-au#60]
The monthly meeting is at 2 pm on Tuesday, 26th March. The zoom link is: 
[https://monash.zoom.us/j/691412731](https://monash.zoom.us/j/691412731)

Draft agenda:

- Discuss v0.3 of the Steering Committee election process

**Comment by manodeep** [comment]
- The program for C3DIS 1-day RSE workshop

**Comment by rowlandm** [comment]
Actually it's Tuesday the 26th of March. Could you edit that first post please Manodeep?

**Comment by manodeep** [comment]
@rowlandm Done!

**Comment by hot007** [comment]
And I'm guessing not 2am either!

**Comment by GerryRyder** [comment]
Can I add an agenda item please?  Will only need 5 minutes

3. ARDC Discovery projects (Gerry)

**Comment by rowlandm** [comment]
RSE-AUNZ Election Process v0.3 is here:
https://docs.google.com/document/d/1P785M_faGGRcBXmg0DSZGJvURM6AaNxWRtMEdbowLHs/edit?usp=sharing

**Comment by rowlandm** [comment]
4. Can we add in a commitment to publish monthly update to the community via email?

**Comment by rowlandm** [comment]
Minutes from the meeting are here:
https://docs.google.com/document/d/1tpJ9d_vC1g3JAEFlG6Ve-yGXs8_30wWcaJQGf3Fd2ag/edit?usp=sharing
