### ISSUE TITLE
News and events to add to newsletters/twitter etc.

### ISSUE THREAD

**Issue by rowlandm** [rse-aunz/rse-au#61]
This is a list for anyone to add in events and news relevant to the RSE AU/NZ community

This includes:

- Events 
- News items
- Articles
- Job listings

**Comment by GerryRyder** [comment]
RSE UK is running a workshop for aspiring RSE leaders.  It will be held in Hampshire on May 1-2.
[See the agenda, learn how to apply. ](https://rse.ac.uk/aspiring-rse-leaders-workshop-1st-2nd-may-2019/)

**Comment by rowlandm** [comment]
Job ad:
https://www.ozgrav.org/data-science-centre-swinburne.html?fbclid=IwAR3ogQZ7Nldf9Jhq-pwm3HSBrDU0JfgUcsZH8uoG0--LHONfisiQyLoiEC0

**Comment by rowlandm** [comment]
Mention this every few months:
I wanted to know how I could help with this Women Working in Openness list:
https://fyoaw.vickysteeves.com/
I was just going to start drawing attention to it online (twitter) and by reaching out to women working at the Uni that I think would like to have the list.

**Comment by GerryRyder** [comment]
A blog post by Karthik Ram reporting back on a recent URSSI workshop on software credit, citation, and metrics software.  Interesting to see the challenges addressed and actions identified during the workshop. http://urssi.us/blog/

**Comment by rowlandm** [comment]
The RSE community might also be interested in the workshop we’ve organised for Thursday morning on education.  Part of that is which organisations play a role in skilling up future RSEs, which will likely be a mix of NCI/Pawsey, universities, and organisations like Intersect and Qcif.

**Comment by rowlandm** [comment]
LEading the Way and Stamina

https://www.veski.org.au/civicrm/mailing/view?reset=1&id=452
