### ISSUE TITLE
Agenda for election process meeting (2019-04-09)

### ISSUE THREAD

**Issue by goldingn** [rse-aunz/rse-au#62]
We'll be holding an additional meeting of the interim steering committee to discuss and decide on the process for the electing the first committee:
https://zoom.us/j/136005389

The topic will be the election process and there won't be time for other matters. Other matters can be  discussed at the next monthly meeting, 2 weeks later.

Draft agenda:

- Recap of proposed methods for ensuring diversity in the election
- Discussion of proposed methods for ensuring diversity in the election
- Discussion of timeframe for the election
- Achieving consensus on the process and amending the document

**Comment by nrmay** [comment]
Proposed methods for _promoting_ diversity in the election:

1. 'Collaborative' selection of a committee.
2. Face-to-face discussion between the candidates, community, and interim steering committee.
3. Candidate criteria (attributes and traits) on the _Call for Nominations_.
3. A _Diversity Statement_ on the _Call for Nominations_.
4. Diversity conditions before closing nominations.
5. Diversity conditions on a ‘properly constituted’ committee.
6. _any other proposals_

**Comment by GerryRyder** [comment]
Documents relevant to the agenda:
--[Election process approved last meeting](https://cloudstor.aarnet.edu.au/plus/s/TjUaYdPodiMABh5#pdfviewer)
--[Draft email to open nomination process ](https://docs.google.com/document/d/1LCROJHk1UMnve2_Ug97DwbHbjEox3qM8U1unph9XKbk/edit)(with comments)
--[C3DIS workshop abstract](http://www.c3dis.com/2965) (accepted)

**Comment by nrmay** [comment]
7. Mandatory Diversity questions on the Nomination.
8. Reserved positions for diversity categories.
