### ISSUE TITLE
Agenda for May meeting 28th May at 2pm AEST

### ISSUE THREAD

**Issue by rowlandm** [rse-aunz/rse-au#63]
1. Jonah Duckles discussion on collaboration with the Carpentries
2. Feedback from C3DIS

**Comment by rowlandm** [comment]
https://monash.zoom.us/j/691412731

**Comment by manodeep** [comment]
3. Discuss a policy for tweet/retweet/likes from the RSE-NZ-AU twitter account

**Comment by rowlandm** [comment]
4. eResearch CFP closes 7th June.

**Comment by rowlandm** [comment]
5. NeSI (@NeSI_NZ) Be part of our 2019 Science Coding Conference programme this September! We're seeking lightning talks, presentations, Birds-of-a-Feather, & workshops on ways writing code & developing applications supports & drives science: https://t.co/3gIDzfr8a1 https://t.co/DEs1juiDgi

**Comment by nrmay** [comment]
6. Election Process v 1.1

**Comment by kerriwait** [comment]
ToDo: look at schedule/info distribution models used by other unconferences

**Comment by rowlandm** [comment]
Notes:
1. Skip til next meeting Jonah [Rowland]
2. C3DIS was worth doing again. Need to write up notes and chase up action items [All]
3. Need to create a policy thread [Manodeep]
4. eResearch should be a mini conference (unconference with profiles of RSEs to also share tech skills and experience) [Rowland]
5. Science Coding Conference could be like eResearch. Need to check 6. [Nooriyah].
6. Need to revisit this before eResearch in October [Nick]

**Comment by nrmay** [comment]
Should read...
6. Need to have agreed process at next meeting (June) so that the election process can be **completed** before the eResearch Australasia conference in October [Nick]

**Comment by nrmay** [comment]
Do we have a list of action items from this meeting?

**Comment by manodeep** [comment]
The action items that I remember were:

- [ ] Putting together a proposal for an RSE unconference at eRA (@rowlandm) 
- [ ] Opening a github issue to discuss Twitter policy for the RSE AU NZ account (@manodeep)
- [ ] Finding out if a half-day RSE unconference session is feasible at NeSI Science Coding (@nooriyahp) 
- [ ] Reading through and providing feedback on Nick's v1.1 of the election document (everyone)

**Comment by nrmay** [comment]
Please can you share the 'proposal for an RSE unconference at eRA', so that we can help and provide input. Thanks.

**Comment by rowlandm** [comment]
Kerri also mentioned that we should have an electronic version of profiles like in the IGW (and in the ResBaz event in 2016 in Brisbane).

**Comment by rowlandm** [comment]
Here is the RSE Mini-conference: eResearch 2019 pre-conference workshop:

https://docs.google.com/document/d/1BAdBgRV8FNypmIagz_div1XnrNF0OajNj4kiC5uSgFk/edit?usp=sharing

**Comment by rowlandm** [comment]
Depending on timing, @nooriyahp  might be doing a similar "mini-conference" at NeSI Science Coding and hopefully we can help with this conference and then re-use the framework for eResearch
