### ISSUE TITLE
Agenda for June meeting 25th June at 2pm AEST

### ISSUE THREAD

**Issue by manodeep** [rse-aunz/rse-au#64]
Zoom link is: https://monash.zoom.us/j/691412731

- Discuss the election process v1.1 document from Nick (rollover from #63)

**Comment by manodeep** [comment]
- Discuss Twitter policy (liking, retweeting, new content)

**Comment by rowlandm** [comment]
- Discuss the idea of having a more RSE friendly component to the meeting by having a talk at say 1.30pm every couple of months, like a mini tech talk? Then we could proceed with the main meeting....

**Comment by nrmay** [comment]
Unfortunately, I can't make this meeting.

Re. Agenda items:
1.  [**election process**](https://docs.google.com/document/d/1mYkxAT6jTsbAkPKDLUH04CKsXkTMUTq7IZIXQJXWMIc) suggestions: 
    - drop elected positions and just elect 8 peopl, then let the committee self organize.
     - drop diversity categories and replace with a mandatory diversity statement from the candidates.
2. **twitter policy** - keep to official notices only (approved by the interim steering committee) until a formal committee has been elected.
3. **tech talks** - not during the steering committee meeting,  as the ARDC already does this and we already occasionally run out of time for our agenda items.

**Comment by HPerrett** [comment]
I'm an apology for today as well 😞


--

Heidi Perrett

Snr Programmer / Software Support

Local Health & Safety Contact



eResearch Support Services

Griffith University | Nathan campus | QLD 4111 | Willett Centre (N53) Room 1.23

T +61 7 373 54344 | M +61 468 989 081  | E h.perrett@griffith.edu.au



griffith.edu.au


[cid:5f3bb72e-389d-4469-87a5-32566e5c8bb2]


Griffith University - CRICOS Provider Number 00233E



PRIVILEGED - PRIVATE AND CONFIDENTIAL

This email and any files transmitted with it are intended solely for the use of the addressee(s) and may contain information which is confidential or privileged. If you receive this email and you are not the addressee or responsible for delivery of the email to the addressee(s), please disregard the contents of the email, delete the mail and notify the author immediately.


________________________________

**Comment by kerriwait** [comment]
I'll just mention this issue that covers our BoF submission (we also have one for the mini conference) https://github.com/rse-aunz/rse-au/issues/68

**Comment by lancewilson-monash** [comment]
Vote for approach to election taken. "Do we attempt to have a collaborative process prior to an election?" 5/8 members voted for including the collaborative process. 

Roland to follow with necessary document changes.

**Comment by rowlandm** [comment]
Out of curiosity, how many abstained from voting Lance?

**Comment by lancewilson-monash** [comment]
There we no abstains and 1 who wanted to vote for both.
