### ISSUE TITLE
Writeup of C3DIS for the RSE community

### ISSUE THREAD

**Issue by rowlandm** [rse-aunz/rse-au#67]
Hi All,

This is the link to the Google Doc for a report on the RSE activities at C3DIS:
https://docs.google.com/document/d/1836W41Ndj_tNtP2fEstU1oNR6HVXQVEX7OMGh_h9MCg/edit

Please feel free to write/review/add comments.

Rowland

**Comment by rowlandm** [comment]
I would like to have this published by Tuesday next week (4th June).

**Comment by manodeep** [comment]
Linking the PR to the webpage is [here](https://github.com/rse-aunz/rse-aunz.github.io/pull/6)

**Comment by rowlandm** [comment]
Workshop link with details

http://bit.ly/rse-c3dis
