### ISSUE TITLE
Agenda for July RSE Interim Steering Committee meeting 23rd July 

### ISSUE THREAD

**Issue by rowlandm** [rse-aunz/rse-au#69]

**Comment by rowlandm** [comment]
Zoom link is: https://monash.zoom.us/j/691412731

1. Finalise a returning officer to kickstart the steering committee selection process by finalising the election process and sharing that with the community.
2. Review of goals for 2019

**Comment by mpfl** [comment]
I'll be an apology for this meeting, I'm afraid, as I'll be delivering a workshop at the same time.

**Comment by hot007** [comment]
What time is the meeting tomorrow?

**Comment by rowlandm** [comment]
2pm Melbourne time

Regards,

Rowland
_______________

Rowland Mosbergen
Petascale Campus Initiative - Facilitator

The University of Melbourne, Victoria 3010 Australia

E:  rowland.mosbergen@unimelb.edu.au

M: +61 3 834 46623


I acknowledge the Wurundjeri people of the Kulin nation as the custodians
of the land on which I work, live, and raise my family. I pay my respects
to their elders past, present and future.

**Comment by rowlandm** [comment]
I may be late to this meeting. Apologies in advance.

**Comment by nrmay** [comment]
**Re. Committee Election Process**
Draft election process document: https://docs.google.com/document/d/1mYkxAT6jTsbAkPKDLUH04CKsXkTMUTq7IZIXQJXWMIc/edit

**For discussion:**

1. Suggest that we simplify. Just elect 8 positions, then let the elected committee self-organize by selecting a chair and secretary.
2. Suggest that the most pragmatic method is to ditch the diverstity categories (which is problematic in itself - given the association with protected attributes) and go with the 'diversity statement' method.
3.  Returning officer is not eligible to nominate.
4. Rowland to outline a collaborative process prior to the election.

**Comment by nrmay** [comment]
**Goals for 2019**

1. Increase awareness of the RSE role/field.
2. Advocating for RSEs.
3. Organizing RSE focused events.
4. Build a diverse community of RSEs.

**Comment by manodeep** [comment]
Include at least one person each from both NZ and AU.

**Comment by manodeep** [comment]
Two levels of collaboration
1. Community based
2. One within the nominees

**Comment by rowlandm** [comment]
Minutes:
ACTION: RM to email Matthias as the returning officer? Ask ARDC.

1. Suggest that we simplify. Just elect 8 positions, then let the elected committee self-organize by selecting a chair and secretary. AGREEMENT.
2. Suggest that the most pragmatic method is to ditch the diverstity categories (which is problematic in itself - given the association with protected attributes) and go with the 'diversity statement' method. AGREEMENT. Provide template. Diversity at least one NZ and one AU at minimum AGREEMENT.
3. Returning officer is not eligible to nominate. AGREEMENT. 
4. Rowland to outline a collaborative process prior to the election. Two levels of collaboration AGREEMENT. Needs to be defined.

**Comment by kerriwait** [comment]
Shall we organise an eResearch mini-conference working committee or something to that effect?

**Comment by rowlandm** [comment]
Good idea. First thing is to ask the people who put their names on the paper ;)

**Comment by HPerrett** [comment]
I'm happy to lead the unconference session

**Comment by rowlandm** [comment]
Heidi to MC and do the first unconference session.

**Comment by rowlandm** [comment]
Ask Sam about leveraging the lunchtime lightning talk presentation area

**Comment by nrmay** [comment]
Election Process has  been updated to reflect the agreed changes.
[Action] Rowland to outline a collaborative process prior to the election.

**Comment by rowlandm** [comment]
I have done the email to Matthias and the collaborative process.
