### ISSUE TITLE
RSE Steering Committee Election 2019 timeline

### ISSUE THREAD

**Issue by mpfl** [rse-aunz/rse-au#70]
Looking at the [election process](https://docs.google.com/document/d/1mYkxAT6jTsbAkPKDLUH04CKsXkTMUTq7IZIXQJXWMIc/edit), the appointment of a Returning Officer and Scrutineer takes place in Week 0.

When should the new committee be in place? If it's to be in time for eResearch Australasia on 21 October, the Call for Nominations will need to take place by Monday 9 September. A couple of weeks of lead time before the Call would help us get it added to various newsletters e.g. AeRO, ARDC.

**Comment by rowlandm** [comment]
That sounds good Matthias. Can we get others from the interim steering
committee to confirm?

Regards,

Rowland
_______________

Rowland Mosbergen
Petascale Campus Initiative - Facilitator

The University of Melbourne, Victoria 3010 Australia

E:  rowland.mosbergen@unimelb.edu.au

M: +61 3 834 46623


I acknowledge the Wurundjeri people of the Kulin nation as the custodians
of the land on which I work, live, and raise my family. I pay my respects
to their elders past, present and future.

**Comment by manodeep** [comment]
@mpfl That timeline should work. 

I also have a memory of discussing whether we should have the collaborative discussion session at eRA. If that is the case, then the timeline might be a little more lenient. 

We have the next Interim Steering Committee meeting next week and we should finalise all the details.

**Comment by mpfl** [comment]
I will be in Adelaide delivering training next week and there's only a moderate chance I'll be able to attend the meeting.

If the interim steering committee can finalise a timeline that gives us at least two weeks (three to four would be better!) before the Call for Nominations at the meeting, that would be great.

**Comment by rowlandm** [comment]
My suggestion would be that week 1 starts on the 2nd September.

That way Week 4 (including the collaboration week) would fall on eResearch
week and the mini- conference, which I think would be useful.

What do others think of that?

Regards,

Rowland
_______________

Rowland Mosbergen
Petascale Campus Initiative - Facilitator

The University of Melbourne, Victoria 3010 Australia

E:  rowland.mosbergen@unimelb.edu.au

M: +61 3 834 46623


I acknowledge the Wurundjeri people of the Kulin nation as the custodians
of the land on which I work, live, and raise my family. I pay my respects
to their elders past, present and future.

**Comment by nrmay** [comment]
Potential Timeline:

1. Acceptance of RO & Scrutineer. Approval of Election process by ISC... due Friday 30th Aug.
2. Nominations Period - start Mon. 2nd Sept.
3. Confirmation Period - start Mon. 16th Sept.
4. Voting Period (if required) - start Mon. 23rd Sept.
6. Collating & Approval of results - starts Mon. 7th Oct.
7. Announcement of results - Mon. 14th Oct.
8. Inaguaral meeting of the Steering Committee - Mon. 21st Oct. (at eResAus2019 workshop.)

**Comment by nrmay** [comment]
# Minutes of the Interim Steering Committee (ISC):
Present: KW, LW, MS, NM, SM.
Aplogies: NL, RM.

## Agenda Items:
1. Committee Election Process (v1.3)
    * Each outstanding comment was discussed and resolved.
    * Sam Moskwa agreed to fulfill the role of Scrutineer for the 2019 election.
    * The option of direct submission on Github was added to the process.
    * It was agreed that the approval of at least half of the wider ISC (i.e. 10) was required for v1.4 to be used for the 2019 process (see action items).
    * It was agreed that the timeline in the previous comment provided the best opportunity to launch the new committee at the RSE mini-conference.
  
2. RSE Mini-conference
    * The organization of the conference was discussed and we agreed that the [RSE Mini-conference Planning doc](https://docs.google.com/document/d/1BAdBgRV8FNypmIagz_div1XnrNF0OajNj4kiC5uSgFk/edit?usp=sharing) provided a sufficient outline of the proceedings on the day.
    *  It was also noted that we cannot wait to the next ISC meeting to progress planning for this event. Therefore, we need to support Heidi Perrett, who has taken overall responsibility for organizing this event. Therefore, it was agreed that we should ask Heidi for a list of action items so that ISC members can volunteer for preparation actions. 

## Actions
**All** -  Review the [Election Process v1.4](https://docs.google.com/document/d/1mYkxAT6jTsbAkPKDLUH04CKsXkTMUTq7IZIXQJXWMIc/edit?usp=sharing) and add you name to the existing comment if you approve this version for the 2019 election. (Due Friday 30th Aug.)
**Manodeep Sinha** - Investigate granting admin rights for the mailing list to Matthias Liffers.
**Matthias Liffers** - Draft a 'Call for Nominations'. (Due Friday 30th Aug.)
**Heidi Perrett** -  Create a list of *preparation* action items for the RSE Mini-conference, and ask for volunteers to take ownership of each item.
**Nick May** - Write up minutes - done.
