### ISSUE TITLE
RSE Interim Steering Committee agenda 27th August at 2pm AEST.

### ISSUE THREAD

**Issue by rowlandm** [rse-aunz/rse-au#71]
Zoom details:
https://monash.zoom.us/j/691412731

Agenda:
1. Election of a new steering committee.
2. RSE mini-conference preparation.

Please add any other agenda items as a separate comment.

**Comment by nrmay** [comment]
Minutes of meeting documented in the following comment:
https://github.com/rse-aunz/rse-au/issues/70#issuecomment-525150606
