### ISSUE TITLE
RSE Interim Steering committee meeting 2pm 24th September 2009

### ISSUE THREAD

**Issue by rowlandm** [rse-aunz/rse-au#81]
https://monash.zoom.us/j/691412731

Agenda items:
1. Election
2. Mini-conference

**Comment by rowlandm** [comment]
For the mini-conference, have a google presentation where people could create a new slide. For the actual posters we could use the eResearch conference poster submission.

**Comment by manodeep** [comment]
Lightning talks are 1-page slide in one big shared google presentation. Further info can also be uploaded as an e-poster and then linked from the 1-page slide.

**Comment by rowlandm** [comment]
Need a time tracker for the BoF and a sign up sheet.

**Comment by rowlandm** [comment]
Introduce the new committee at the BoF (and the Mini-conference).

**Comment by rowlandm** [comment]
Perhaps we could have a expectation setting document for what an unconference.

**Comment by rowlandm** [comment]
Nooriyah to chase up things for the BoF that came out of this meeting, Rowland to chase up things for the mini-conference that came out of this meeting.

**Comment by rowlandm** [comment]
Poster link is here:
https://conference.eresearch.edu.au/guidelines-for-eposter-presenters/

Actual upload is here:
https://www.dropbox.com/request/gFfZXRfH4bjuU72lrRHp
