### ISSUE TITLE
RSE Steering Committee Meeting No. 1

### ISSUE THREAD

**Issue by mpfl** [rse-aunz/rse-au#82]
Agenda

* Selection of Chair
* Selection of Secretary
* Casual vacancies
* eResearch Australasia 2019
* Where to from here?

**Comment by nrmay** [comment]
Detailed Agenda (proposed)
1. Election of the Chair
    1. Duties of the Chair
        * Ensure activities are aligned with the goals of the association.
        * Run committee meetings.
    1. Nominations
    2. Vote
2. Election of the secretary
    * Duties of the secretary
        * Manage timing and agenda of committee meetings.
        * Publish minutes of committee meetings.
        * Ensure assets are secured for the association. E.g. Websites, social media accounts, etc.
    * Nominations
    * Vote
3. Process for appointing additional casual vacancies.
4. Assignment of deliverables.
    * Publish a Manifesto or Mission Statement
    * Define Personas, Profiles, or Personal Stories of the people that form the RSE community.
    * Create Impact Stories to inform organizations about RSE.
    * Establish a permanent Web Presence to be launched at eResearch Australasia 2019.
    * Run Face-to-face Meetings and grow contacts in states and regional areas not yet engaged.
    * Create an Info Pack for Local RSE Groups.
5. eResearch Australasia 2019
6. Any Other Business

**Comment by mpfl** [comment]
Outcome of office bearer roles:

Nooriyah Poonawala-Lohani and Heidi Perrett are Co-Chairs of the RSE Committee
Nick May is Secretary

**Comment by nrmay** [comment]
# Minutes of Steering Committee Meeting No.1
## 2019.10.17
## *FINAL*
### Attendees
* [DC] Daniel Collins
* [HP] Heidi Perrett
* [JB] Justin Baker
* [NL] Nooriyah Poonawala-Lohani
* [NM] Nicholas May
* [MS] Manodeep Sinha
* [ML] Matthias Liffers (Chair for agenda items 1. & 2.)

### Discussion
For the detailed agenda see above.

#### Election of Chair.
* The duties as described were accepted.
* Two candidates were nominated.
* It was proposed, and accepted unanimously, that both candidates should share the position, as this ease the operation of this role in the inaugural year and would support representation across AU and NZ.
* HP and NL were elected co-chairs of the SC.

#### Election of Secretary.
* The duties as described were accepted.
* One candidate was nominated and it was accepted unanimously.
* NM was elected secretary of the SC.

#### Casual Vacancies.
* There are two positions vacant.
* The goal in appointing two additional members should be to increase the diversity of representation on the committee. It was noted that the SC lacks representation in WA, SA, TAS, and NSW, and has limited representation from active academics.
* It was agreed that SC should:
  * invite potential candidates to submit an application,
  * publicize the vacancies via social media and mailing list, and 
  * publicize the vacancies at the RSE Mini-conference (Mon. 21st Oct.).

#### Deliverables 2019.
* There was much discussion about the 'Web Presence' deliverable. Specifically, about the scope and practicality of the proposed deadline. In addition, the long term sustainability of any solution will have to be addressed, given that RSE-AUNZ is not yet financial and has not been formally constituted. Some options were raised for future discussion.
* It was agreed that the deliverables should be reviewed at the next meeting, in the light of feedback from the RSE BoF (eResAus2019), to determine relevance and alignment with future goals.
* Assignment will be postponed until after the review.

#### eResearch Australasia 2019 (eResAus2019)
* BoF:  It was agreed to use the Goals for 2019 as the initial discussion points. NM agreed to moderate the discussion section.
* Mini-conference: A request was made for volunteers to fill specific roles during the event.  Volunteers came forward, and all roles have now been filled. 


#### Any other business:
* It was agreed that the SC should meet fortnightly at this early stage of operation and then review the periodicity as necessary.

### Actions
* [HP] 	Draft a slide outlining an invitation for candidates to submit an application regarding the casual vacancies.
* [NM]	Share the Goals and Deliverables 2019 to Rebecca Lange, for the BoF slides.
* [DC]	Set-up a shared Google Drive folder for collaborative documents of the SC.
* [NL]	Create a Doodle poll to schedule the next meeting.
* [NM]	Draft the minutes of the meeting.
* [All]	Review minutes and add comments for clarification/amendments.
* [NM]	Publish final version of the minutes on the Github repository.

### Next Meeting
* Oct 29-30th - Date/time to be confirmed.

### Notes
These minutes have been drafted under part of the Chatham House Rule. This promotes openness, and inclusion, by not attributing any specific comment to any individual/s. The exception is that participants are necessarily listed as attendees of the Steering Committee meeting.
