### ISSUE TITLE
getting involved

### ISSUE THREAD

**Issue by goldingn** [rse-aunz/rse-au#9]
Hi folks,

I'd be really keen to help build up a community of RSEs in Australia. What would be the best way to get involved?

Nick

P.S. I'm an academic, based in Melbourne, and spend (or try to spend) most of my research time writing software in R for statistics, ecology and public health research. I also do ad-hoc training, system administration and events organisation, and review software papers in an ecology journal.

**Comment by rowlandm** [comment]
Hi Nick - that would be great!

Would you like to help organise a meetup for Victorians around this? Lance from Monash also put his hand up previously. There are no concrete plans yet, as we have been focusing on a Perth meeting.

Speaking of which, you can help by promoting the event that is in Perth on the 18th of May!

https://www.eventbrite.com.au/e/research-software-engineers-au-meetup-in-perth-tickets-45844919388?aff=efbneb

**Comment by goldingn** [comment]
Yes, I'd be very happy to help organise a Vic meetup! I'll get in touch with Lance.

Would that meetup be like the Perth one - an open invitation to discuss setting up an organisation?

Great, I'll tweet about the Perth meetup now!

**Comment by rowlandm** [comment]
Yes - exactly, just a kick off to start a discussion.

Medium term plan is to have a national meeting like the Tech Talks to run as part of eResearch 2018

**Comment by dylan-jayatilaka** [comment]
I am sorry to miss your meeting in WA on Friday.
I am a Prof. at UWA. We do quantum chemistry & crystallography.
Luckily my research mostly coincides with programming new methods.
We are selling a GUI software products. It is based on free software.
Long term we want to curate the data generated by our products and sell that as an alternative way to fund our research.
I don't have much time but I think this kind of a discussion and grouping is long missing,
I don't see many stable STEM jobs out there for my students, I also don't see a
good recognition of math/computing/simulation training in chemistry and biology at Uni's
despite it being sorely needed and despite that people use the software heavily as "users" -
there is a massive gap between industry requirements and skill levels at Uni .  SOme startups
from ex students but very few and far between.
I hope I can help in some way.

**Comment by rowlandm** [comment]
Hi everyone,

The link to apply for membership to the Google Group is:
https://groups.google.com/forum/#!forum/rse-nz-au

Simply login to a google account and then select "Apply for Membership"
